# Generated by Django 4.2.11 on 2025-11-04 19:54

import cadastros.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(db_index=True, max_length=50)),
                ('apelido_loja', models.CharField(db_index=True, max_length=20)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[cadastros.validators.cnpj_validator])),
                ('logradouro', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True, validators=[cadastros.validators.cep_validator])),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=15, null=True, validators=[cadastros.validators.telefone_br_validator])),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True, validators=[cadastros.validators.telefone_br_validator])),
                ('email', models.CharField(blank=True, max_length=50, null=True, validators=[cadastros.validators.email_simple_validator])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_cadastro', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['cnpj'], name='cadastros_l_cnpj_f075a2_idx'), models.Index(fields=['cidade', 'estado'], name='cadastros_l_cidade_59ea22_idx'), models.Index(fields=['ativo'], name='cadastros_l_ativo_ce754c_idx'), models.Index(fields=['data_cadastro'], name='cadastros_l_data_ca_1eec55_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(db_index=True, max_length=50)),
                ('apelido', models.CharField(blank=True, db_index=True, max_length=18, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[cadastros.validators.cnpj_validator])),
                ('logradouro', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True, validators=[cadastros.validators.cep_validator])),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=15, null=True, validators=[cadastros.validators.telefone_br_validator])),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True, validators=[cadastros.validators.telefone_br_validator])),
                ('email', models.CharField(blank=True, max_length=50, null=True, validators=[cadastros.validators.email_simple_validator])),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('bloqueio', models.BooleanField(db_index=True, default=False)),
                ('mala_direta', models.BooleanField(db_index=True, default=False)),
                ('conta_contabil', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_cadastro', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['cnpj'], name='cadastros_f_cnpj_a533e1_idx'), models.Index(fields=['cidade', 'estado'], name='cadastros_f_cidade_c6197b_idx'), models.Index(fields=['categoria'], name='cadastros_f_categor_b28379_idx'), models.Index(fields=['bloqueio'], name='cadastros_f_bloquei_0d3c51_idx'), models.Index(fields=['mala_direta'], name='cadastros_f_mala_di_be1b4c_idx'), models.Index(fields=['ativo'], name='cadastros_f_ativo_df199b_idx'), models.Index(fields=['data_cadastro'], name='cadastros_f_data_ca_0f28a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(db_index=True, max_length=50)),
                ('apelido', models.CharField(blank=True, db_index=True, max_length=18, null=True)),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[cadastros.validators.cpf_validator])),
                ('logradouro', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True, validators=[cadastros.validators.cep_validator])),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=15, null=True, validators=[cadastros.validators.telefone_br_validator])),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True, validators=[cadastros.validators.telefone_br_validator])),
                ('email', models.CharField(blank=True, max_length=50, null=True, validators=[cadastros.validators.email_simple_validator])),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('bloqueio', models.BooleanField(db_index=True, default=False)),
                ('aniversario', models.DateField(blank=True, db_index=True, null=True)),
                ('mala_direta', models.BooleanField(db_index=True, default=False)),
                ('conta_contabil', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_cadastro', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['cpf'], name='cadastros_c_cpf_8dd2d2_idx'), models.Index(fields=['cidade', 'estado'], name='cadastros_c_cidade_f8864d_idx'), models.Index(fields=['categoria'], name='cadastros_c_categor_03632c_idx'), models.Index(fields=['bloqueio'], name='cadastros_c_bloquei_f489ec_idx'), models.Index(fields=['mala_direta'], name='cadastros_c_mala_di_21cca8_idx'), models.Index(fields=['ativo'], name='cadastros_c_ativo_c27f03_idx'), models.Index(fields=['data_cadastro'], name='cadastros_c_data_ca_2bfa16_idx')],
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomefuncionario', models.CharField(db_index=True, max_length=50)),
                ('apelido', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[cadastros.validators.cpf_validator])),
                ('inicio', models.DateField(blank=True, db_index=True, null=True)),
                ('fim', models.DateField(blank=True, db_index=True, null=True)),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('meta', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_cadastro', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('idloja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='cadastros.loja')),
            ],
            options={
                'indexes': [models.Index(fields=['idloja'], name='cadastros_f_idloja__494ed7_idx'), models.Index(fields=['categoria'], name='cadastros_f_categor_1fc1bf_idx'), models.Index(fields=['ativo'], name='cadastros_f_ativo_3a385f_idx'), models.Index(fields=['data_cadastro'], name='cadastros_f_data_ca_ca8ef0_idx')],
            },
        ),
    ]
