# Generated by Django 4.2.11 on 2025-11-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nat_Lancamento',
            fields=[
                ('idnatureza', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('categoria_principal', models.CharField(max_length=50)),
                ('subcategoria', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('tipo_natureza', models.CharField(max_length=10)),
            ],
        ),
    ]
