# Generated by Django 4.2.11 on 2025-11-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_nat_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='ContaContabil',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='DataAbertura',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='DataEnceramento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='EstoqueNegativo',
            field=models.CharField(blank=True, default='NAO', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='Matriz',
            field=models.CharField(blank=True, default='NAO', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='Rede',
            field=models.CharField(blank=True, default='NAO', max_length=3, null=True),
        ),
    ]
