# Generated by Django 4.2.11 on 2026-05-30 23:27

from django.db import migrations, models


def preencher_comissao_vendedores(apps, schema_editor):
    Funcionarios = apps.get_model('cadastros', 'Funcionarios')
    Funcionarios.objects.filter(categoria__iexact='Vendedor').update(comissao_percentual=5)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_loja_contacontabil_loja_dataabertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.RunPython(preencher_comissao_vendedores, migrations.RunPython.noop),
    ]
