# Generated by Django 4.2.11 on 2026-07-05 13:29

import cadastros.validators
from django.db import migrations, models
import django.db.models.deletion


def vincular_naturezas_empresa(apps, schema_editor):
    Empresa = apps.get_model('cadastros', 'Empresa')
    NatLancamento = apps.get_model('cadastros', 'Nat_Lancamento')

    empresas = list(Empresa.objects.order_by('id'))
    if not empresas:
        return
    empresa_padrao = empresas[0]
    NatLancamento.objects.filter(empresa__isnull=True).update(empresa=empresa_padrao)

    base = list(NatLancamento.objects.filter(empresa=empresa_padrao).order_by('idnatureza'))
    for empresa in empresas[1:]:
        for natureza in base:
            NatLancamento.objects.get_or_create(
                empresa=empresa,
                codigo=natureza.codigo,
                defaults={
                    'categoria_principal': natureza.categoria_principal,
                    'subcategoria': natureza.subcategoria,
                    'descricao': natureza.descricao,
                    'tipo': natureza.tipo,
                    'status': natureza.status,
                    'tipo_natureza': natureza.tipo_natureza,
                },
            )


def desvincular_naturezas_empresa(apps, schema_editor):
    NatLancamento = apps.get_model('cadastros', 'Nat_Lancamento')
    NatLancamento.objects.update(empresa=None)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_cliente_fornecedor_funcionario_empresa'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='empresa',
            new_name='cadastros_e_nome_1ec0bf_idx',
            old_name='cadastros_e_nome_c3e4c1_idx',
        ),
        migrations.RenameIndex(
            model_name='empresa',
            new_name='cadastros_e_nome_fa_35ff97_idx',
            old_name='cadastros_e_nome_fa_5de0ca_idx',
        ),
        migrations.RenameIndex(
            model_name='empresa',
            new_name='cadastros_e_ativo_899fca_idx',
            old_name='cadastros_e_ativo_04efdd_idx',
        ),
        migrations.AddField(
            model_name='nat_lancamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='naturezas_lancamento', to='cadastros.empresa'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, validators=[cadastros.validators.cnpj_validator]),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(max_length=18, validators=[cadastros.validators.cnpj_validator]),
        ),
        migrations.RunPython(vincular_naturezas_empresa, desvincular_naturezas_empresa),
        migrations.AddConstraint(
            model_name='fornecedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'cnpj'), name='uq_empresa_fornecedor_cnpj'),
        ),
        migrations.AddConstraint(
            model_name='loja',
            constraint=models.UniqueConstraint(fields=('empresa', 'cnpj'), name='uq_empresa_loja_cnpj'),
        ),
    ]
