# Generated by Django 4.2.11 on 2026-07-07 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_nat_lancamento_campos_gerenciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=160)),
                ('classe', models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('PATRIMONIO', 'Patrimônio líquido'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('RESULTADO', 'Resultado')], db_index=True, max_length=20)),
                ('natureza', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('analitica', models.BooleanField(db_index=True, default=True)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('conta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcontas', to='cadastros.planocontabil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plano_contabil', to='cadastros.empresa')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='nat_lancamento',
            name='plano_contabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='naturezas_lancamento', to='cadastros.planocontabil'),
        ),
        migrations.AddIndex(
            model_name='planocontabil',
            index=models.Index(fields=['empresa', 'codigo'], name='cadastros_p_empresa_0fedc1_idx'),
        ),
        migrations.AddIndex(
            model_name='planocontabil',
            index=models.Index(fields=['empresa', 'classe'], name='cadastros_p_empresa_35ee71_idx'),
        ),
        migrations.AddIndex(
            model_name='planocontabil',
            index=models.Index(fields=['empresa', 'ativa'], name='cadastros_p_empresa_142480_idx'),
        ),
        migrations.AddConstraint(
            model_name='planocontabil',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_empresa_plano_contabil_codigo'),
        ),
    ]
