# Generated by Django 4.2.11 on 2026-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_planocontabil_nat_lancamento_plano_contabil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocontabil',
            name='classe',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('PATRIMONIO', 'Patrimônio líquido'), ('RECEITA', 'Receita'), ('CUSTO', 'Custo'), ('DESPESA', 'Despesa'), ('RESULTADO', 'Resultado')], db_index=True, max_length=20),
        ),
    ]
