# Generated by Django 4.2.11 on 2026-07-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_loja_tipo_unidade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='empresa',
            new_name='cadastros_e_usa_pro_af07c1_idx',
            old_name='cadastros_e_usa_pro_9d9f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='loja',
            new_name='cadastros_l_tipo_un_8f83d4_idx',
            old_name='cadastros_l_tipo_u_9df230_idx',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ambiente_fiscal',
            field=models.CharField(choices=[('HOMOLOGACAO', 'Homologação'), ('PRODUCAO', 'Produção')], db_index=True, default='HOMOLOGACAO', max_length=12),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='proximo_numero_nfce',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='proximo_numero_nfe',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regime_tributario',
            field=models.CharField(choices=[('SIMPLES', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real')], db_index=True, default='SIMPLES', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='serie_nfce',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='serie_nfe',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uf_fiscal',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
