# Generated by Django 4.2.11 on 2026-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_rename_cadastros_e_usa_pro_9d9f8d_idx_cadastros_e_usa_pro_af07c1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='ambiente_fiscal',
            field=models.CharField(choices=[('HOMOLOGACAO', 'Homologação'), ('PRODUCAO', 'Produção')], db_index=True, default='HOMOLOGACAO', max_length=12),
        ),
        migrations.AddField(
            model_name='loja',
            name='emite_nfce',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='emite_nfe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='proximo_numero_nfce',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loja',
            name='proximo_numero_nfe',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loja',
            name='regime_tributario',
            field=models.CharField(choices=[('SIMPLES', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real')], db_index=True, default='SIMPLES', max_length=20),
        ),
        migrations.AddField(
            model_name='loja',
            name='serie_nfce',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loja',
            name='serie_nfe',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
