# Generated by Django 4.2.11 on 2026-07-13 14:33

from django.db import migrations, models


def habilitar_master_empresas_existentes(apps, schema_editor):
    Empresa = apps.get_model('cadastros', 'Empresa')
    Empresa.objects.update(
        licenca_master=True,
        usa_vendas=True,
        usa_compras=True,
        usa_estoque=True,
        usa_financeiro=True,
        usa_fiscal=True,
        usa_producao=True,
        usa_ficha_tecnica=True,
        usa_faccao=True,
        usa_distribuicao_producao=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_loja_ambiente_fiscal_loja_emite_nfce_loja_emite_nfe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='licenca_master',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usa_compras',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usa_estoque',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usa_financeiro',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usa_fiscal',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usa_vendas',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(habilitar_master_empresas_existentes, migrations.RunPython.noop),
    ]
