# Generated by Codex on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0016_empresa_licenca_master_empresa_usa_compras_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionarios",
            name="salario",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
