# Generated by Django 4.2.11 on 2026-08-04 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


MODULES = [
    ("operacional", "Operacional", "BASICO", True, 10, []),
    ("cadastros", "Cadastros", "BASICO", True, 20, []),
    ("produtos", "Produtos", "BASICO", True, 30, []),
    ("configuracoes", "Configurações", "BASICO", True, 40, []),
    ("vendas", "Vendas", "COMERCIAL", False, 100, ["cadastros", "produtos"]),
    ("compras", "Compras", "COMERCIAL", False, 110, ["cadastros", "produtos"]),
    ("estoque", "Estoque", "COMERCIAL", False, 120, ["produtos"]),
    ("financeiro", "Financeiro", "COMERCIAL", False, 130, ["cadastros"]),
    ("fiscal", "Fiscal", "COMERCIAL", False, 140, ["cadastros"]),
    ("producao", "Produção", "COMERCIAL", False, 150, ["produtos", "estoque"]),
    ("distribuicao", "Distribuição", "COMERCIAL", False, 160, ["estoque"]),
    ("relatorios", "Relatórios", "COMERCIAL", False, 170, []),
    ("auditoria", "Auditoria", "INTERNO", False, 900, []),
]


def seed_contracts_and_modules(apps, schema_editor):
    Empresa = apps.get_model("cadastros", "Empresa")
    ModuloSistema = apps.get_model("cadastros", "ModuloSistema")
    EmpresaContrato = apps.get_model("cadastros", "EmpresaContrato")
    EmpresaModulo = apps.get_model("cadastros", "EmpresaModulo")
    User = apps.get_model("accounts", "User")
    today = django.utils.timezone.localdate()

    modulo_by_key = {}
    for chave, nome, categoria, basico, ordem, deps in MODULES:
        modulo, _ = ModuloSistema.objects.update_or_create(
            chave=chave,
            defaults={
                "nome": nome,
                "descricao": "",
                "categoria": categoria,
                "basico": basico,
                "ativo": True,
                "ordem": ordem,
                "dependencias": deps,
            },
        )
        modulo_by_key[chave] = modulo

    legacy_map = {
        "usa_vendas": "vendas",
        "usa_compras": "compras",
        "usa_estoque": "estoque",
        "usa_financeiro": "financeiro",
        "usa_fiscal": "fiscal",
        "usa_producao": "producao",
        "usa_distribuicao_producao": "distribuicao",
    }

    for empresa in Empresa.objects.all():
        plano = bool(getattr(empresa, "licenca_master", False) or getattr(empresa, "plano_completo", False))
        if empresa.plano_completo != plano:
            empresa.plano_completo = plano
            empresa.save(update_fields=["plano_completo"])
        active_users = User.objects.filter(empresa=empresa, is_active=True, is_superuser=False).count()
        master = None
        admins = list(User.objects.filter(empresa=empresa, is_active=True, is_superuser=False, type="Admin").order_by("date_joined", "id")[:2])
        if len(admins) == 1:
            master = admins[0]
        EmpresaContrato.objects.update_or_create(
            empresa=empresa,
            defaults={
                "status": "ATIVO" if empresa.ativo else "SUSPENSO",
                "data_inicio": getattr(empresa, "data_cadastro", None).date() if getattr(empresa, "data_cadastro", None) else today,
                "limite_usuarios": max(active_users, 1),
                "plano_completo": plano,
                "usuario_master": master,
                "observacoes": "Criado automaticamente pela migração inicial de licenciamento.",
                "permissions_version": 1,
            },
        )
        for field, key in legacy_map.items():
            EmpresaModulo.objects.update_or_create(
                empresa=empresa,
                modulo=modulo_by_key[key],
                defaults={"contratado": bool(getattr(empresa, field, False)), "data_inicio": today},
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_permissions'),
        ('cadastros', '0017_funcionarios_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plano_completo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(db_index=True, max_length=40, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(choices=[('BASICO', 'Básico'), ('COMERCIAL', 'Comercial'), ('INTERNO', 'Interno')], db_index=True, max_length=20)),
                ('basico', models.BooleanField(db_index=True, default=False)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('ordem', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('dependencias', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['chave'], name='cadastros_m_chave_c433ad_idx'), models.Index(fields=['basico', 'ativo'], name='cadastros_m_basico_891caa_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=12)),
                ('data_inicio', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True)),
                ('limite_usuarios', models.PositiveIntegerField(default=1)),
                ('plano_completo', models.BooleanField(db_index=True, default=False)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('permissions_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='cadastros.empresa')),
                ('usuario_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratado', models.BooleanField(db_index=True, default=False)),
                ('data_inicio', models.DateField(blank=True, db_index=True, null=True)),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modulos_contratados', to='cadastros.empresa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_modulo', to='cadastros.modulosistema')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'contratado'], name='cadastros_e_empresa_4ea6c4_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='cadastros_e_data_in_ca7668_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='empresamodulo',
            constraint=models.UniqueConstraint(fields=('empresa', 'modulo'), name='uq_empresa_modulo'),
        ),
        migrations.AddIndex(
            model_name='empresacontrato',
            index=models.Index(fields=['status', 'data_inicio', 'data_fim'], name='cadastros_e_status_98e80b_idx'),
        ),
        migrations.AddIndex(
            model_name='empresacontrato',
            index=models.Index(fields=['plano_completo'], name='cadastros_e_plano_c_2bac9f_idx'),
        ),
        migrations.RunPython(seed_contracts_and_modules, noop),
    ]
