# Generated by Django 4.2.11 on 2026-08-04 17:59

from django.db import migrations, models


def copy_limite_usuarios(apps, schema_editor):
    EmpresaContrato = apps.get_model("cadastros", "EmpresaContrato")
    for contrato in EmpresaContrato.objects.all():
        contrato.limite_sessoes_simultaneas = max(1, int(contrato.limite_usuarios or 1))
        contrato.save(update_fields=["limite_sessoes_simultaneas"])


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_empresa_plano_completo_modulosistema_empresacontrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacontrato',
            name='limite_sessoes_simultaneas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(copy_limite_usuarios, migrations.RunPython.noop),
    ]
