# Generated by Django 4.2.11 on 2026-08-05 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0020_modulo_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacontrato',
            name='motivo_suspensao',
            field=models.CharField(blank=True, choices=[('INADIMPLENCIA', 'Inadimplência'), ('SOLICITACAO_CLIENTE', 'Solicitação do cliente'), ('RISCO_SEGURANCA', 'Risco de segurança'), ('ENCERRAMENTO_CONTRATO', 'Encerramento de contrato'), ('BLOQUEIO_ADMINISTRATIVO', 'Bloqueio administrativo'), ('OUTRO', 'Outro')], db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='empresacontrato',
            name='observacao_suspensao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='empresacontrato',
            name='reativado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresacontrato',
            name='reativado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_reativados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresacontrato',
            name='suspenso_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresacontrato',
            name='suspenso_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_suspensos', to=settings.AUTH_USER_MODEL),
        ),
    ]
