# Generated by Django 4.2.11 on 2026-08-09 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_rename_prazo_pagamento_parcela_index'),
        ('cadastros', '0024_fornecedor_fase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='conta_contabil_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores_padrao', to='cadastros.planocontabil'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='prazo_padrao_pagamento_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores_padrao', to='financeiro.prazopagamento'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='contribuinte_icms',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('ISENTO', 'Isento')], max_length=20, null=True),
        ),
    ]
