# Generated by Django 4.2.11 on 2026-08-11 21:11

import cadastros.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def normalizar_codigo(valor):
    base = "".join(ch for ch in (valor or "").strip().upper() if ch.isalnum())
    return (base or "CARGO")[:20]


def somente_digitos(valor):
    return "".join(ch for ch in (valor or "") if ch.isdigit()) or None


def migrar_funcionarios(apps, schema_editor):
    Cargo = apps.get_model("cadastros", "Cargo")
    Funcionarios = apps.get_model("cadastros", "Funcionarios")
    por_empresa = {}
    for func in Funcionarios.objects.select_related("empresa").all().order_by("empresa_id", "id"):
        if not func.empresa_id:
            continue
        updates = []
        cpf = somente_digitos(func.cpf)
        if func.cpf != cpf:
            func.cpf = cpf
            updates.append("cpf")
        seq = por_empresa.setdefault(func.empresa_id, 0) + 1
        por_empresa[func.empresa_id] = seq
        if not func.matricula:
            func.matricula = str(seq).zfill(6)
            updates.append("matricula")
        categoria = (func.categoria or "").strip()
        if categoria and not func.cargo_id:
            codigo_base = normalizar_codigo(categoria)
            codigo = codigo_base
            sufixo = 1
            while Cargo.objects.filter(empresa_id=func.empresa_id, codigo=codigo).exclude(descricao__iexact=categoria).exists():
                sufixo += 1
                codigo = f"{codigo_base[:16]}{sufixo:04d}"[:20]
            cargo, _ = Cargo.objects.get_or_create(
                empresa_id=func.empresa_id,
                codigo=codigo,
                defaults={
                    "descricao": categoria[:80],
                    "ativo": True,
                    "participa_vendas": categoria.lower().strip() == "vendedor",
                    "permite_comissao": categoria.lower().strip() == "vendedor",
                    "autoridade_operacional_loja": categoria.lower().strip() in {"vendedor", "caixa", "gerente"},
                    "gerencial": categoria.lower().strip() in {"gerente", "supervisor"},
                    "permite_multiplas_lojas": categoria.lower().strip() == "supervisor",
                },
            )
            func.cargo_id = cargo.pk
            updates.append("cargo")
        if func.cargo_id:
            cargo = Cargo.objects.get(pk=func.cargo_id)
            if cargo.participa_vendas and not func.participa_vendas:
                func.participa_vendas = True
                updates.append("participa_vendas")
            if cargo.permite_comissao and (func.comissao_percentual or 0) > 0:
                func.comissionado = True
                updates.append("comissionado")
        if func.ativo is False and func.situacao == "ATIVO":
            func.situacao = "DESLIGADO" if func.fim else "AFASTADO"
            updates.append("situacao")
        if updates:
            func.save(update_fields=sorted(set(updates)))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0025_fornecedor_conta_contabil_padrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(db_index=True, max_length=80)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('participa_vendas', models.BooleanField(db_index=True, default=False)),
                ('permite_comissao', models.BooleanField(db_index=True, default=False)),
                ('autoridade_operacional_loja', models.BooleanField(db_index=True, default=False)),
                ('permite_multiplas_lojas', models.BooleanField(db_index=True, default=False)),
                ('gerencial', models.BooleanField(db_index=True, default=False)),
                ('data_cadastro', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARGO', 'Mudança de cargo'), ('LOJA', 'Mudança de loja'), ('ABRANGENCIA', 'Alteração de abrangência'), ('AFASTAMENTO', 'Afastamento'), ('RETORNO', 'Retorno'), ('DESLIGAMENTO', 'Desligamento'), ('RECONTRATACAO', 'Recontratação')], db_index=True, max_length=20)),
                ('data_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_novo', models.JSONField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=120, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_hora', '-id'],
            },
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='comissionado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='email',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[cadastros.validators.email_simple_validator]),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='endereco',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='lojas_supervisionadas',
            field=models.ManyToManyField(blank=True, related_name='funcionarios_abrangencia', to='cadastros.loja'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='matricula',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='participa_vendas',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('AFASTADO', 'Afastado'), ('DESLIGADO', 'Desligado')], db_index=True, default='ATIVO', max_length=12),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[cadastros.validators.telefone_br_validator]),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='todas_lojas_da_empresa',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[cadastros.validators.telefone_br_validator]),
        ),
        migrations.AddIndex(
            model_name='funcionarios',
            index=models.Index(fields=['empresa', 'matricula'], name='idx_func_emp_matricula'),
        ),
        migrations.AddIndex(
            model_name='funcionarios',
            index=models.Index(fields=['empresa', 'cpf'], name='idx_func_emp_cpf'),
        ),
        migrations.AddIndex(
            model_name='funcionarios',
            index=models.Index(fields=['empresa', 'situacao'], name='idx_func_emp_situacao'),
        ),
        migrations.AddField(
            model_name='funcionariohistorico',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios_historico', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='funcionariohistorico',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='cadastros.funcionarios'),
        ),
        migrations.AddField(
            model_name='funcionariohistorico',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios_historico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='cadastros.cargo'),
        ),
        migrations.RunPython(migrar_funcionarios, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='funcionarios',
            constraint=models.UniqueConstraint(fields=('empresa', 'matricula'), name='uq_empresa_funcionario_matricula'),
        ),
        migrations.AddConstraint(
            model_name='funcionarios',
            constraint=models.UniqueConstraint(fields=('empresa', 'cpf'), name='uq_empresa_funcionario_cpf'),
        ),
        migrations.AddIndex(
            model_name='funcionariohistorico',
            index=models.Index(fields=['empresa', 'funcionario', 'data_hora'], name='idx_funchist_emp_func_data'),
        ),
        migrations.AddIndex(
            model_name='funcionariohistorico',
            index=models.Index(fields=['empresa', 'tipo'], name='idx_funchist_emp_tipo'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['empresa', 'ativo'], name='idx_cargo_empresa_ativo'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['empresa', 'descricao'], name='idx_cargo_empresa_desc'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_empresa_cargo_codigo'),
        ),
    ]
