# Generated by Django 4.2.11 on 2026-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_centrocusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='codigo_municipio_ibge',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
