# Generated by Django 4.2.11 on 2025-11-04 19:54

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('custom', 'Custom')], max_length=12)),
                ('app_label', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('changes', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app_label', 'model'], name='auditoria_a_app_lab_37e0c5_idx'), models.Index(fields=['action'], name='auditoria_a_action_1263d1_idx'), models.Index(fields=['created_at'], name='auditoria_a_created_c9eca7_idx')],
            },
        ),
    ]
