# Generated by Django 4.2.11 on 2025-11-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_resize_audit_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditoria_a_action_1263d1_idx',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='auditoria_auditlog',
        ),
    ]
