# Generated by Django 4.2.11 on 2026-07-29 18:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0027_inventario_validacao_contado'),
        ('cadastros', '0017_funcionarios_salario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=24)),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('PERCENTUAL', 'Percentual'), ('FIXA', 'Quantidade fixa'), ('METRICA', 'Métrica')], db_index=True, default='MANUAL', max_length=12)),
                ('origem_operacao', models.CharField(choices=[('MANUAL', 'Manual'), ('PRODUCAO', 'Produção'), ('COMPRA', 'Compra')], default='MANUAL', max_length=12)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASC', 'Rascunho'), ('CALC', 'Calculada'), ('CONF', 'Confirmada'), ('PED', 'Pedidos gerados'), ('FATUR', 'Em faturamento'), ('NF', 'Faturada'), ('TRANS', 'Em trânsito'), ('PARC', 'Parcialmente recebida'), ('RECB', 'Recebida'), ('CANC', 'Cancelada')], db_index=True, default='RASC', max_length=8)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('quantidade_total', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('valor_total_custo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_total_venda', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribuicoes_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribuicoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuicoes', to='cadastros.empresa')),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DistribuicaoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sugerida', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantidade_ajustada', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantidade_confirmada', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentual', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('prioridade', models.PositiveIntegerField(default=0)),
                ('bloqueado_recalculo', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RASC', 'Rascunho'), ('CONF', 'Confirmado'), ('PED', 'Pedido gerado'), ('CANC', 'Cancelado')], db_index=True, default='RASC', max_length=4)),
                ('distribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='distribuicao.distribuicao')),
            ],
            options={
                'ordering': ['loja_destino_id', 'item_id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoVendaDistribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=24)),
                ('data_pedido', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('AB', 'Aberto'), ('AGF', 'Aguardando faturamento'), ('FAT', 'Faturado'), ('CANC', 'Cancelado')], db_index=True, default='AGF', max_length=4)),
                ('quantidade_total', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('valor_total_custo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_total_venda', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('faturamento_status', models.CharField(db_index=True, default='AGUARDANDO_FATURAMENTO', max_length=30)),
                ('nfe_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('nfe_chave', models.CharField(blank=True, max_length=44, null=True)),
                ('nfe_status', models.CharField(blank=True, max_length=30, null=True)),
                ('nfe_data', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('distribuicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda', to='distribuicao.distribuicao')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda_distribuicao', to='cadastros.empresa')),
                ('loja_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda_distribuicao_destino', to='cadastros.loja')),
                ('unidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda_distribuicao_origem', to='cadastros.loja')),
            ],
            options={
                'ordering': ['-data_pedido', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilDistribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('PERCENTUAL', 'Percentual'), ('FIXA', 'Quantidade fixa'), ('METRICA', 'Métrica')], db_index=True, default='PERCENTUAL', max_length=12)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_distribuicao_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis_distribuicao', to='cadastros.empresa')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PedidoVendaDistribuicaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=30)),
                ('descricao', models.CharField(max_length=140)),
                ('cor_descricao', models.CharField(blank=True, max_length=80, null=True)),
                ('tamanho_descricao', models.CharField(blank=True, max_length=40, null=True)),
                ('ean13', models.CharField(db_index=True, max_length=13)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_custo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_item', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('distribuicao_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_itens', to='distribuicao.distribuicaodestino')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='distribuicao.pedidovendadistribuicao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produtodetalhe')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MercadoriaTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean13', models.CharField(db_index=True, max_length=13)),
                ('quantidade_enviada', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantidade_recebida', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantidade_divergente', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AG_EXP', 'Aguardando expedição'), ('TRANS', 'Em trânsito'), ('RECB', 'Recebida'), ('DIV', 'Divergente')], db_index=True, default='AG_EXP', max_length=8)),
                ('distribuicao_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitos', to='distribuicao.distribuicaodestino')),
                ('loja_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercadorias_transito_destino', to='cadastros.loja')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitos', to='distribuicao.pedidovendadistribuicao')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitos', to='distribuicao.pedidovendadistribuicaoitem')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produtodetalhe')),
                ('unidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercadorias_transito_origem', to='cadastros.loja')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DistribuicaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=30)),
                ('descricao', models.CharField(max_length=140)),
                ('cor_descricao', models.CharField(blank=True, max_length=80, null=True)),
                ('tamanho_descricao', models.CharField(blank=True, max_length=40, null=True)),
                ('ean13', models.CharField(db_index=True, max_length=13)),
                ('estoque_fisico', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('estoque_reservado', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('estoque_disponivel', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantidade_selecionada', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bloqueado_recalculo', models.BooleanField(default=False)),
                ('distribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='distribuicao.distribuicao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_distribuicao', to='produto.produto')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_distribuicao', to='produto.produtodetalhe')),
            ],
            options={
                'ordering': ['referencia', 'cor_descricao', 'tamanho_descricao'],
            },
        ),
        migrations.AddField(
            model_name='distribuicaodestino',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='distribuicao.distribuicaoitem'),
        ),
        migrations.AddField(
            model_name='distribuicaodestino',
            name='loja_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuicoes_destino', to='cadastros.loja'),
        ),
        migrations.AddField(
            model_name='distribuicaodestino',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos', to='distribuicao.pedidovendadistribuicao'),
        ),
        migrations.AddField(
            model_name='distribuicaodestino',
            name='pedido_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_distribuicao', to='distribuicao.pedidovendadistribuicaoitem'),
        ),
        migrations.AddField(
            model_name='distribuicao',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuicoes', to='distribuicao.perfildistribuicao'),
        ),
        migrations.AddField(
            model_name='distribuicao',
            name='unidade_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuicoes_origem', to='cadastros.loja'),
        ),
        migrations.CreateModel(
            name='PerfilDistribuicaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantidade_fixa', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('prioridade', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis_distribuicao', to='cadastros.loja')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='distribuicao.perfildistribuicao')),
            ],
            options={
                'ordering': ['prioridade', 'loja_id'],
                'indexes': [models.Index(fields=['perfil', 'ativo'], name='distribuica_perfil__f3c156_idx'), models.Index(fields=['loja'], name='distribuica_loja_id_b9bbf6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='perfildistribuicaoitem',
            constraint=models.UniqueConstraint(fields=('perfil', 'loja'), name='uq_perfil_distribuicao_loja'),
        ),
        migrations.AddIndex(
            model_name='perfildistribuicao',
            index=models.Index(fields=['empresa', 'ativo'], name='distribuica_empresa_f6dff1_idx'),
        ),
        migrations.AddIndex(
            model_name='perfildistribuicao',
            index=models.Index(fields=['tipo'], name='distribuica_tipo_b678ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='perfildistribuicao',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_empresa_perfil_distribuicao_codigo'),
        ),
        migrations.AddIndex(
            model_name='pedidovendadistribuicaoitem',
            index=models.Index(fields=['pedido', 'referencia'], name='distribuica_pedido__7c9dad_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidovendadistribuicaoitem',
            index=models.Index(fields=['sku'], name='distribuica_sku_id_ffd7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidovendadistribuicao',
            index=models.Index(fields=['empresa', 'status'], name='distribuica_empresa_91672c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidovendadistribuicao',
            index=models.Index(fields=['loja_destino', 'data_pedido'], name='distribuica_loja_de_5b8a20_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidovendadistribuicao',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uq_empresa_pedido_venda_distribuicao_numero'),
        ),
        migrations.AddConstraint(
            model_name='pedidovendadistribuicao',
            constraint=models.UniqueConstraint(fields=('distribuicao', 'loja_destino'), name='uq_distribuicao_pedido_loja'),
        ),
        migrations.AddIndex(
            model_name='mercadoriatransito',
            index=models.Index(fields=['loja_destino', 'status'], name='distribuica_loja_de_e354c1_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadoriatransito',
            index=models.Index(fields=['ean13'], name='distribuica_ean13_a71b7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mercadoriatransito',
            constraint=models.UniqueConstraint(fields=('pedido_item',), name='uq_transito_pedido_item_distribuicao'),
        ),
        migrations.AddIndex(
            model_name='distribuicaoitem',
            index=models.Index(fields=['distribuicao', 'referencia'], name='distribuica_distrib_d26ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='distribuicaoitem',
            index=models.Index(fields=['sku'], name='distribuica_sku_id_506f74_idx'),
        ),
        migrations.AddConstraint(
            model_name='distribuicaoitem',
            constraint=models.UniqueConstraint(fields=('distribuicao', 'sku'), name='uq_distribuicao_sku'),
        ),
        migrations.AddIndex(
            model_name='distribuicaodestino',
            index=models.Index(fields=['distribuicao', 'loja_destino'], name='distribuica_distrib_a7c58b_idx'),
        ),
        migrations.AddIndex(
            model_name='distribuicaodestino',
            index=models.Index(fields=['status'], name='distribuica_status_1f7cef_idx'),
        ),
        migrations.AddConstraint(
            model_name='distribuicaodestino',
            constraint=models.UniqueConstraint(fields=('item', 'loja_destino'), name='uq_distribuicao_item_loja'),
        ),
        migrations.AddIndex(
            model_name='distribuicao',
            index=models.Index(fields=['empresa', 'status'], name='distribuica_empresa_8b324b_idx'),
        ),
        migrations.AddIndex(
            model_name='distribuicao',
            index=models.Index(fields=['unidade_origem', 'data'], name='distribuica_unidade_0b79f3_idx'),
        ),
        migrations.AddIndex(
            model_name='distribuicao',
            index=models.Index(fields=['data'], name='distribuica_data_662a54_idx'),
        ),
        migrations.AddConstraint(
            model_name='distribuicao',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uq_empresa_distribuicao_numero'),
        ),
    ]
