# Generated by Django 4.2.11 on 2026-07-29 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distribuicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuicao',
            name='data',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='pedidovendadistribuicao',
            name='data_pedido',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
