# Generated by Django 4.2.11 on 2026-07-29 22:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


def _q4(value):
    return Decimal(value or 0).quantize(Decimal('0.0001'))


def _money(value):
    return Decimal(value or 0).quantize(Decimal('0.01'))


def backfill_distribuicao_precos(apps, schema_editor):
    Distribuicao = apps.get_model('distribuicao', 'Distribuicao')
    DistribuicaoItem = apps.get_model('distribuicao', 'DistribuicaoItem')
    PedidoVendaDistribuicao = apps.get_model('distribuicao', 'PedidoVendaDistribuicao')
    PedidoVendaDistribuicaoItem = apps.get_model('distribuicao', 'PedidoVendaDistribuicaoItem')
    PerfilDistribuicao = apps.get_model('distribuicao', 'PerfilDistribuicao')
    PerfilDistribuicaoItem = apps.get_model('distribuicao', 'PerfilDistribuicaoItem')
    Loja = apps.get_model('cadastros', 'Loja')

    for item in DistribuicaoItem.objects.select_related('sku', 'produto'):
        sku = item.sku
        produto = item.produto
        custo = _q4(
            getattr(sku, 'custo_medio', 0)
            or getattr(sku, 'custo_ultima_compra', 0)
            or getattr(sku, 'custo_original', 0)
            or getattr(produto, 'custo_medio', 0)
            or getattr(produto, 'custo_ultima_compra', 0)
            or getattr(produto, 'custo_original', 0)
            or 0
        )
        if custo > 0 and _q4(item.custo_unitario) != custo:
            item.custo_unitario = custo
            item.custo_total = _money(Decimal(item.quantidade_selecionada or 0) * custo)
            item.save(update_fields=['custo_unitario', 'custo_total'])

    for pedido_item in PedidoVendaDistribuicaoItem.objects.select_related('pedido__distribuicao', 'sku', 'produto'):
        sku = pedido_item.sku
        produto = pedido_item.produto
        fator = Decimal(getattr(pedido_item.pedido.distribuicao, 'fator_preco', Decimal('0.2000')) or 0)
        custo = _q4(
            getattr(sku, 'custo_medio', 0)
            or getattr(sku, 'custo_ultima_compra', 0)
            or getattr(sku, 'custo_original', 0)
            or getattr(produto, 'custo_medio', 0)
            or getattr(produto, 'custo_ultima_compra', 0)
            or getattr(produto, 'custo_original', 0)
            or 0
        )
        if custo <= 0:
            continue
        preco = _q4(custo * (Decimal('1') + fator))
        pedido_item.custo_unitario = custo
        pedido_item.preco_unitario = preco
        pedido_item.total_custo = _money(Decimal(pedido_item.quantidade or 0) * custo)
        pedido_item.total_item = _money(Decimal(pedido_item.quantidade or 0) * preco)
        pedido_item.save(update_fields=['custo_unitario', 'preco_unitario', 'total_custo', 'total_item'])

    for pedido in PedidoVendaDistribuicao.objects.all():
        itens = PedidoVendaDistribuicaoItem.objects.filter(pedido=pedido)
        pedido.quantidade_total = sum((Decimal(i.quantidade or 0) for i in itens), Decimal('0.000'))
        pedido.valor_total_custo = sum((Decimal(i.total_custo or 0) for i in itens), Decimal('0.00'))
        pedido.valor_total_venda = sum((Decimal(i.total_item or 0) for i in itens), Decimal('0.00'))
        pedido.save(update_fields=['quantidade_total', 'valor_total_custo', 'valor_total_venda'])

    for dist in Distribuicao.objects.all():
        destinos = dist.destinos.filter(status__in=['RASC', 'CONF', 'PED'])
        qtd = Decimal('0.000')
        custo = Decimal('0.00')
        for destino in destinos.select_related('item'):
            quantidade = Decimal(destino.quantidade_confirmada or destino.quantidade_ajustada or destino.quantidade_sugerida or 0)
            qtd += quantidade
            custo += quantidade * Decimal(destino.item.custo_unitario or 0)
        dist.quantidade_total = qtd
        dist.valor_total_custo = _money(custo)
        dist.valor_total_venda = _money(custo * (Decimal('1') + Decimal(dist.fator_preco or 0)))
        dist.save(update_fields=['quantidade_total', 'valor_total_custo', 'valor_total_venda'])

    for perfil in PerfilDistribuicao.objects.filter(ativo=True):
        if PerfilDistribuicaoItem.objects.filter(perfil=perfil).exists():
            continue
        lojas = list(Loja.objects.filter(empresa_id=perfil.empresa_id, ativo=True).exclude(tipo_unidade='FABRICA').order_by('id'))
        if not lojas:
            continue
        percentuais = []
        desc = f'{perfil.codigo} {perfil.descricao}'
        if len(lojas) == 2 and '40' in desc and '60' in desc:
            percentuais = [Decimal('40.0000'), Decimal('60.0000')]
        else:
            base = (Decimal('100.0000') / Decimal(len(lojas))).quantize(Decimal('0.0001'))
            percentuais = [base for _ in lojas]
            percentuais[-1] = Decimal('100.0000') - sum(percentuais[:-1], Decimal('0.0000'))
        for index, loja in enumerate(lojas):
            PerfilDistribuicaoItem.objects.create(
                perfil=perfil,
                loja=loja,
                percentual=percentuais[index],
                quantidade_fixa=Decimal('0.000'),
                prioridade=index + 1,
                ativo=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('distribuicao', '0002_alter_distribuicao_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuicao',
            name='fator_preco',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='perfildistribuicao',
            name='fator_preco',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(backfill_distribuicao_precos, migrations.RunPython.noop),
    ]
