# Generated by Django 4.2.11 on 2026-05-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Vendedor', 'Vendedor'), ('Caixa', 'Caixa'), ('Gerente', 'Gerente'), ('Diretor', 'Diretor'), ('Admin', 'Admin'), ('Auxiliar', 'Auxiliar'), ('Assistente', 'Assistente'), ('AssistenteReceber', 'Assistente contas a receber'), ('AssistentePagar', 'Assistente contas a pagar')], default='Regular', max_length=20),
        ),
    ]
