# Generated by Codex on 2026-07-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_lojas"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModulePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("cadastros", "Cadastros"),
                            ("produtos", "Produtos"),
                            ("fiscal", "Fiscal"),
                            ("estoque", "Estoque"),
                            ("vendas", "Vendas"),
                            ("compras", "Compras"),
                            ("producao", "Produção"),
                            ("financeiro", "Financeiro"),
                            ("relatorios", "Relatórios"),
                            ("configuracoes", "Configurações"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "acesso",
                    models.CharField(
                        choices=[("NONE", "Sem acesso"), ("VIEW", "Somente consulta"), ("EDIT", "Consulta e edição")],
                        db_index=True,
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["user_id", "modulo"]},
        ),
        migrations.CreateModel(
            name="UserFieldPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "campo",
                    models.CharField(
                        choices=[
                            ("funcionario.salario", "Funcionário - salário"),
                            ("produto.custo", "Produto - custos e margens"),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                ("pode_ver", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["user_id", "campo"]},
        ),
        migrations.AddConstraint(
            model_name="usermodulepermission",
            constraint=models.UniqueConstraint(fields=("user", "modulo"), name="uq_user_module_permission"),
        ),
        migrations.AddConstraint(
            model_name="userfieldpermission",
            constraint=models.UniqueConstraint(fields=("user", "campo"), name="uq_user_field_permission"),
        ),
    ]
