# Generated by Django 4.2.11 on 2026-08-04 14:09

from django.db import migrations, models
import django.db.models.deletion


PROFILE_PERMISSIONS = {
    "Administrador delegado": {
        "operacional": "EDIT", "cadastros": "EDIT", "produtos": "EDIT", "configuracoes": "EDIT",
        "vendas": "EDIT", "compras": "EDIT", "estoque": "EDIT", "financeiro": "EDIT",
        "fiscal": "EDIT", "producao": "EDIT", "distribuicao": "EDIT", "relatorios": "VIEW",
    },
    "Gerente": {
        "operacional": "VIEW", "cadastros": "EDIT", "produtos": "EDIT", "configuracoes": "VIEW",
        "vendas": "EDIT", "compras": "VIEW", "estoque": "EDIT", "financeiro": "VIEW",
        "fiscal": "VIEW", "producao": "VIEW", "distribuicao": "EDIT", "relatorios": "VIEW",
    },
    "Vendedor": {"cadastros": "VIEW", "produtos": "VIEW", "vendas": "VIEW", "estoque": "VIEW"},
    "Caixa": {"cadastros": "VIEW", "produtos": "VIEW", "vendas": "EDIT", "financeiro": "VIEW", "estoque": "VIEW"},
    "Financeiro": {"cadastros": "VIEW", "financeiro": "EDIT", "relatorios": "VIEW"},
    "Compras": {"cadastros": "VIEW", "produtos": "VIEW", "compras": "EDIT", "fiscal": "VIEW"},
    "Estoque": {"produtos": "VIEW", "estoque": "EDIT", "distribuicao": "VIEW"},
    "Fiscal": {"cadastros": "VIEW", "fiscal": "EDIT", "financeiro": "VIEW"},
    "Regular": {"cadastros": "VIEW", "produtos": "VIEW"},
}


def create_profiles_and_assign(apps, schema_editor):
    Empresa = apps.get_model("cadastros", "Empresa")
    ModuloSistema = apps.get_model("cadastros", "ModuloSistema")
    EmpresaContrato = apps.get_model("cadastros", "EmpresaContrato")
    EmpresaModulo = apps.get_model("cadastros", "EmpresaModulo")
    PerfilAcesso = apps.get_model("accounts", "PerfilAcesso")
    PerfilModuloPermissao = apps.get_model("accounts", "PerfilModuloPermissao")
    User = apps.get_model("accounts", "User")

    module_by_key = {m.chave: m for m in ModuloSistema.objects.all()}

    def available(empresa):
        try:
            contrato = EmpresaContrato.objects.get(empresa=empresa)
        except EmpresaContrato.DoesNotExist:
            return set()
        keys = set(ModuloSistema.objects.filter(ativo=True, basico=True).values_list("chave", flat=True))
        if contrato.plano_completo:
            keys.update(ModuloSistema.objects.filter(ativo=True, basico=False, categoria="COMERCIAL").values_list("chave", flat=True))
            return keys
        keys.update(EmpresaModulo.objects.filter(empresa=empresa, contratado=True, modulo__ativo=True).values_list("modulo__chave", flat=True))
        return keys

    type_profile = {
        "Admin": "Administrador delegado",
        "Diretor": "Administrador delegado",
        "Gerente": "Gerente",
        "Vendedor": "Vendedor",
        "Caixa": "Caixa",
        "AssistenteReceber": "Financeiro",
        "AssistentePagar": "Compras",
        "Auxiliar": "Estoque",
        "Assistente": "Regular",
        "Regular": "Regular",
    }

    for empresa in Empresa.objects.all():
        available_keys = available(empresa)
        profiles = {}
        for name, perms in PROFILE_PERMISSIONS.items():
            perfil, _ = PerfilAcesso.objects.get_or_create(
                empresa=empresa,
                nome=name,
                defaults={"descricao": "Perfil criado pela migração inicial.", "ativo": True, "padrao": name == "Regular"},
            )
            profiles[name] = perfil
            for key, access in perms.items():
                modulo = module_by_key.get(key)
                if not modulo:
                    continue
                PerfilModuloPermissao.objects.update_or_create(
                    perfil=perfil,
                    modulo=modulo,
                    defaults={"acesso": access if key in available_keys else "NONE"},
                )
        for user in User.objects.filter(empresa=empresa, is_superuser=False):
            if user.perfil_principal_id:
                continue
            profile_name = type_profile.get(getattr(user, "type", "Regular") or "Regular", "Regular")
            user.perfil_principal = profiles.get(profile_name) or profiles.get("Regular")
            user.save(update_fields=["perfil_principal"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_empresa_plano_completo_modulosistema_empresacontrato_and_more'),
        ('accounts', '0005_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('padrao', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis_acesso', to='cadastros.empresa')),
            ],
            options={
                'ordering': ['empresa_id', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='usermodulepermission',
            name='modulo',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('cadastros', 'Cadastros'), ('produtos', 'Produtos'), ('fiscal', 'Fiscal'), ('fiscal_contabil', 'Fiscal e Contábil'), ('estoque', 'Estoque'), ('distribuicao', 'Distribuição'), ('vendas', 'Vendas'), ('compras', 'Compras'), ('producao', 'Produção'), ('financeiro', 'Financeiro'), ('relatorios', 'Relatórios'), ('configuracoes', 'Configurações')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='PerfilModuloPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso', models.CharField(choices=[('NONE', 'Sem acesso'), ('VIEW', 'Somente consulta'), ('EDIT', 'Consulta e edição')], db_index=True, default='NONE', max_length=10)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissoes_perfis', to='cadastros.modulosistema')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_modulos', to='accounts.perfilacesso')),
            ],
            options={
                'ordering': ['perfil_id', 'modulo__ordem'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='perfil_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='accounts.perfilacesso'),
        ),
        migrations.AddConstraint(
            model_name='perfilmodulopermissao',
            constraint=models.UniqueConstraint(fields=('perfil', 'modulo'), name='uq_perfil_modulo_permission'),
        ),
        migrations.AddIndex(
            model_name='perfilacesso',
            index=models.Index(fields=['empresa', 'ativo'], name='accounts_pe_empresa_cb6000_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilacesso',
            index=models.Index(fields=['padrao', 'ativo'], name='accounts_pe_padrao_f8417d_idx'),
        ),
        migrations.AddConstraint(
            model_name='perfilacesso',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uq_perfil_acesso_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='perfilacesso',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('padrao', True)), fields=('empresa',), name='uq_perfil_padrao_ativo_empresa'),
        ),
        migrations.RunPython(create_profiles_and_assign, noop),
    ]
