# Generated by Django 4.2.11 on 2026-08-04 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_empresacontrato_limite_sessoes_simultaneas'),
        ('accounts', '0007_remove_perfil_default_state_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_key_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('dispositivo_id', models.CharField(db_index=True, max_length=128)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade_em', models.DateTimeField(db_index=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_encerramento', models.CharField(blank=True, default='', max_length=50)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_usuarios', to='cadastros.empresa')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_usuarios', to='cadastros.loja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_acesso', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_token', to='accounts.sessaousuario')),
            ],
        ),
        migrations.AddIndex(
            model_name='sessaousuario',
            index=models.Index(fields=['empresa', 'ativa'], name='accounts_se_empresa_5ae708_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaousuario',
            index=models.Index(fields=['usuario', 'ativa'], name='accounts_se_usuario_e31ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaousuario',
            index=models.Index(fields=['dispositivo_id'], name='accounts_se_disposi_4101dc_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaousuario',
            index=models.Index(fields=['ultima_atividade_em'], name='accounts_se_ultima__fdfc88_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaousuario',
            index=models.Index(fields=['empresa', 'ativa', 'ultima_atividade_em'], name='accounts_se_empresa_1b7b42_idx'),
        ),
    ]
