# Generated by Django 4.2.11 on 2026-08-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usermodulepermission_auditoria_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deve_trocar_senha',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
