# Generated by Django 4.2.11 on 2026-08-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_permissions_consolidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprocesspermission',
            name='codigo',
            field=models.CharField(choices=[('requisicoes.fazer', 'Requisições - fazer'), ('requisicoes.aprovar', 'Requisições - aprovar'), ('requisicoes.atender', 'Requisições - atender'), ('cotacao.aprovar', 'Cotação - aprovar'), ('pedido_compra.aprovar', 'Pedido de compra - aprovar'), ('vendas.autorizar_desconto', 'Vendas - autorizar desconto'), ('funcionario.salario', 'Funcionário - salário'), ('produto.custo', 'Produto - custos e margens')], db_index=True, max_length=80),
        ),
    ]
