# Generated by Django 4.2.11 on 2026-09-13 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_perfilprocesspermission_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialPdvUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha_hash', models.CharField(max_length=128)),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial_pdv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario_id'],
                'indexes': [models.Index(fields=['habilitado', 'usuario'], name='ix_cred_pdv_hab_user')],
            },
        ),
    ]
