# Generated by Django 4.2.11 on 2026-01-02 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='55', max_length=2)),
                ('serie', models.CharField(blank=True, default='', max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('chave_acesso', models.CharField(blank=True, default='', max_length=60)),
                ('dt_emissao', models.DateField()),
                ('dt_entrada', models.DateField()),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('FE', 'Fechada'), ('CA', 'Cancelada')], db_index=True, default='AB', max_length=2)),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nfe_entrada_criadas', to=settings.AUTH_USER_MODEL)),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_entrada', to='compras.pedidocompra')),
            ],
            options={
                'db_table': 'fiscal_nota_fiscal_entrada',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEntradaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_recebida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('preco_unit_nf', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.notafiscalentrada')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_nf_entrada', to='compras.pedidocompraitem')),
            ],
            options={
                'db_table': 'fiscal_nota_fiscal_entrada_item',
                'indexes': [models.Index(fields=['nota'], name='ix_fiscal_nfe_item_nota'), models.Index(fields=['pedido_item'], name='ix_fiscal_nfe_item_pedido_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='notafiscalentradaitem',
            constraint=models.UniqueConstraint(fields=('nota', 'pedido_item'), name='uq_fiscal_nfe_item_nota_pedido_item'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['pedido_compra', 'status'], name='ix_fiscal_nfe_pedido_status'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['modelo', 'serie', 'numero'], name='ix_fiscal_nfe_num'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalentrada',
            constraint=models.UniqueConstraint(fields=('pedido_compra', 'modelo', 'serie', 'numero'), name='uq_fiscal_nfe_pedido_modelo_serie_numero'),
        ),
    ]
