# Generated by Django 4.2.11 on 2026-05-30 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_inventarioestoque_estoquemovimentacao_and_more'),
        ('cadastros', '0003_loja_contacontabil_loja_dataabertura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaPdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='FINALIZADA', max_length=12)),
                ('forma_pagamento', models.CharField(max_length=30)),
                ('data_venda', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('desconto_itens', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('desconto_geral', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('troco', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv', to='cadastros.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv', to='cadastros.loja')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv', to='cadastros.funcionarios')),
            ],
            options={
                'db_table': 'fiscal_venda_pdv',
                'ordering': ['-data_venda', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NFCe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(default='HOMOLOGACAO', max_length=12)),
                ('modelo', models.CharField(default='65', max_length=2)),
                ('serie', models.PositiveIntegerField(default=1)),
                ('numero', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('DIGITADA', 'Digitada'), ('EMITINDO', 'Emitindo'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada'), ('CONTINGENCIA', 'Contingencia')], db_index=True, default='DIGITADA', max_length=12)),
                ('chave_acesso', models.CharField(blank=True, db_index=True, default='', max_length=44)),
                ('protocolo', models.CharField(blank=True, default='', max_length=30)),
                ('qr_code_url', models.TextField(blank=True, default='')),
                ('xml', models.TextField(blank=True, default='')),
                ('retorno_codigo', models.CharField(blank=True, default='', max_length=10)),
                ('retorno_mensagem', models.CharField(blank=True, default='', max_length=255)),
                ('autorizada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nfce', to='fiscal.vendapdv')),
            ],
            options={
                'db_table': 'fiscal_nfce',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='VendaPdvItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(db_index=True, max_length=13)),
                ('referencia', models.CharField(blank=True, default='', max_length=30)),
                ('descricao', models.CharField(max_length=120)),
                ('cor', models.CharField(blank=True, default='', max_length=80)),
                ('tamanho', models.CharField(blank=True, default='', max_length=30)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_item', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produtodetalhe')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.vendapdv')),
            ],
            options={
                'db_table': 'fiscal_venda_pdv_item',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['venda'], name='ix_venda_pdv_item_venda'), models.Index(fields=['ean'], name='ix_venda_pdv_item_ean')],
            },
        ),
        migrations.AddIndex(
            model_name='vendapdv',
            index=models.Index(fields=['loja', 'data_venda'], name='ix_venda_pdv_loja_data'),
        ),
        migrations.AddIndex(
            model_name='vendapdv',
            index=models.Index(fields=['cliente', 'data_venda'], name='ix_venda_pdv_cliente_data'),
        ),
        migrations.AddIndex(
            model_name='vendapdv',
            index=models.Index(fields=['status'], name='ix_venda_pdv_status'),
        ),
        migrations.AddIndex(
            model_name='nfce',
            index=models.Index(fields=['status'], name='ix_nfce_status'),
        ),
        migrations.AddIndex(
            model_name='nfce',
            index=models.Index(fields=['chave_acesso'], name='ix_nfce_chave'),
        ),
        migrations.AddConstraint(
            model_name='nfce',
            constraint=models.UniqueConstraint(fields=('serie', 'numero'), name='uq_nfce_serie_numero'),
        ),
    ]
