# Generated by Django 4.2.11 on 2026-05-31 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_caixa_options_caixa_tipo_caixa_and_more'),
        ('fiscal', '0002_vendapdv_nfce_vendapdvitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendapdv',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv', to='financeiro.caixa'),
        ),
        migrations.AddIndex(
            model_name='vendapdv',
            index=models.Index(fields=['caixa', 'data_venda'], name='ix_venda_pdv_caixa_data'),
        ),
    ]
