# Generated by Django 4.2.11 on 2026-06-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_vendapdv_caixa_vendapdv_ix_venda_pdv_caixa_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaPdvPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(db_index=True, max_length=30)),
                ('descricao', models.CharField(blank=True, default='', max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('autorizacao', models.CharField(blank=True, default='', max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='fiscal.vendapdv')),
            ],
            options={
                'db_table': 'fiscal_venda_pdv_pagamento',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['venda'], name='ix_venda_pdv_pag_venda'), models.Index(fields=['forma'], name='ix_venda_pdv_pag_forma')],
            },
        ),
    ]
