# Generated by Codex on 2026-06-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0004_funcionarios_comissao_percentual"),
        ("fiscal", "0004_vendapdvpagamento"),
        ("produto", "0007_inventarioestoque_estoquemovimentacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendaDevolucao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("documento", models.CharField(db_index=True, max_length=50, unique=True)),
                ("status", models.CharField(choices=[("DIGITADA", "Digitada"), ("FINALIZADA", "Finalizada"), ("CANCELADA", "Cancelada")], db_index=True, default="FINALIZADA", max_length=12)),
                ("motivo", models.CharField(blank=True, default="", max_length=255)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("credito_cliente", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="devolucoes_venda", to="cadastros.cliente")),
                ("criado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="devolucoes_venda_criadas", to=settings.AUTH_USER_MODEL)),
                ("loja", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="devolucoes_venda", to="cadastros.loja")),
                ("venda", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="devolucoes", to="fiscal.vendapdv")),
            ],
            options={
                "db_table": "fiscal_venda_devolucao",
                "ordering": ["-criado_em", "-id"],
                "indexes": [
                    models.Index(fields=["venda"], name="ix_devolucao_venda"),
                    models.Index(fields=["loja", "criado_em"], name="ix_devolucao_loja_data"),
                    models.Index(fields=["cliente", "criado_em"], name="ix_devolucao_cliente_data"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendaDevolucaoItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ean", models.CharField(db_index=True, max_length=13)),
                ("referencia", models.CharField(blank=True, default="", max_length=30)),
                ("descricao", models.CharField(max_length=120)),
                ("cor", models.CharField(blank=True, default="", max_length=80)),
                ("tamanho", models.CharField(blank=True, default="", max_length=30)),
                ("quantidade", models.PositiveIntegerField()),
                ("preco_unitario", models.DecimalField(decimal_places=4, max_digits=18)),
                ("desconto", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_item", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("devolucao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="fiscal.vendadevolucao")),
                ("produto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="produto.produto")),
                ("sku", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="produto.produtodetalhe")),
                ("venda_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="devolucoes_itens", to="fiscal.vendapdvitem")),
            ],
            options={
                "db_table": "fiscal_venda_devolucao_item",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["devolucao"], name="ix_devolucao_item_dev"),
                    models.Index(fields=["venda_item"], name="ix_devolucao_item_venda"),
                    models.Index(fields=["ean"], name="ix_devolucao_item_ean"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NFeDevolucao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ambiente", models.CharField(default="HOMOLOGACAO", max_length=12)),
                ("modelo", models.CharField(default="55", max_length=2)),
                ("serie", models.PositiveIntegerField(default=1)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                ("status", models.CharField(choices=[("DIGITADA", "Digitada"), ("EMITINDO", "Emitindo"), ("AUTORIZADA", "Autorizada"), ("REJEITADA", "Rejeitada"), ("CANCELADA", "Cancelada")], db_index=True, default="DIGITADA", max_length=12)),
                ("chave_acesso", models.CharField(blank=True, db_index=True, default="", max_length=44)),
                ("protocolo", models.CharField(blank=True, default="", max_length=30)),
                ("xml", models.TextField(blank=True, default="")),
                ("retorno_codigo", models.CharField(blank=True, default="", max_length=10)),
                ("retorno_mensagem", models.CharField(blank=True, default="", max_length=255)),
                ("autorizada_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("devolucao", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="nfe_devolucao", to="fiscal.vendadevolucao")),
                ("nfce_origem", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="nfes_devolucao", to="fiscal.nfce")),
            ],
            options={
                "db_table": "fiscal_nfe_devolucao",
                "ordering": ["-numero"],
                "constraints": [models.UniqueConstraint(fields=("serie", "numero"), name="uq_nfe_devolucao_serie_numero")],
                "indexes": [
                    models.Index(fields=["status"], name="ix_nfe_devolucao_status"),
                    models.Index(fields=["chave_acesso"], name="ix_nfe_devolucao_chave"),
                ],
            },
        ),
    ]
