# Generated by Django 4.2.11 on 2026-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_vendapdvitem_cmv_total_vendapdvitem_custo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendadevolucaoitem',
            name='cmv_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendadevolucaoitem',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
