# Generated by Django 4.2.11 on 2026-07-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0008_vendadevolucaoitem_cmv_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendapdvitem',
            name='aliquota_cofins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='aliquota_icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='aliquota_pis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='base_cofins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='base_icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='base_pis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='cfop',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='cst_cofins',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='cst_icms',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='cst_pis',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='ncm',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='origem_mercadoria',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='total_impostos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='valor_cofins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='valor_icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendapdvitem',
            name='valor_pis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
