# Generated by Django 4.2.11 on 2026-07-13 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def popular_cfops_iniciais(apps, schema_editor):
    Empresa = apps.get_model('cadastros', 'Empresa')
    Cfop = apps.get_model('fiscal', 'Cfop')
    cfops = [
        ("5102", "Venda de mercadoria adquirida ou recebida de terceiros", "VENDA", "DENTRO_UF", True, True),
        ("6102", "Venda de mercadoria adquirida ou recebida de terceiros", "VENDA", "FORA_UF", True, True),
        ("5101", "Venda de produção do estabelecimento", "VENDA", "DENTRO_UF", True, True),
        ("6101", "Venda de produção do estabelecimento", "VENDA", "FORA_UF", True, True),
        ("1102", "Compra para comercialização", "COMPRA", "DENTRO_UF", True, True),
        ("2102", "Compra para comercialização", "COMPRA", "FORA_UF", True, True),
        ("1202", "Devolução de venda de mercadoria adquirida de terceiros", "DEVOLUCAO", "DENTRO_UF", True, True),
        ("2202", "Devolução de venda de mercadoria adquirida de terceiros", "DEVOLUCAO", "FORA_UF", True, True),
        ("1411", "Devolução de venda de mercadoria em operação com substituição tributária", "DEVOLUCAO", "DENTRO_UF", True, True),
        ("5405", "Venda de mercadoria adquirida com substituição tributária", "VENDA", "DENTRO_UF", True, True),
        ("5929", "Lançamento relativo a emissão de cupom fiscal", "VENDA", "DENTRO_UF", True, True),
    ]
    for empresa in Empresa.objects.all():
        for codigo, descricao, tipo, destino, estoque, financeiro in cfops:
            Cfop.objects.update_or_create(
                empresa=empresa,
                codigo=codigo,
                defaults={
                    "descricao": descricao,
                    "tipo_operacao": tipo,
                    "destino": destino,
                    "movimenta_estoque": estoque,
                    "gera_financeiro": financeiro,
                    "ativo": True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_empresa_licenca_master_empresa_usa_compras_and_more'),
        ('fiscal', '0009_vendapdvitem_aliquota_cofins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cfop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'CFOP deve ter 4 dígitos.')])),
                ('descricao', models.CharField(max_length=255)),
                ('tipo_operacao', models.CharField(choices=[('VENDA', 'Venda'), ('COMPRA', 'Compra'), ('DEVOLUCAO', 'Devolução'), ('TRANSFERENCIA', 'Transferência'), ('OUTROS', 'Outros')], db_index=True, default='OUTROS', max_length=20)),
                ('destino', models.CharField(choices=[('DENTRO_UF', 'Dentro do estado'), ('FORA_UF', 'Fora do estado'), ('AMBOS', 'Ambos')], db_index=True, default='AMBOS', max_length=12)),
                ('movimenta_estoque', models.BooleanField(default=True)),
                ('gera_financeiro', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cfops', to='cadastros.empresa')),
            ],
            options={
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['empresa', 'codigo'], name='fiscal_cfop_empresa_ded858_idx'), models.Index(fields=['tipo_operacao', 'destino'], name='fiscal_cfop_tipo_op_a0302e_idx'), models.Index(fields=['ativo'], name='fiscal_cfop_ativo_9020b8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cfop',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_cfop_empresa_codigo'),
        ),
        migrations.RunPython(popular_cfops_iniciais, migrations.RunPython.noop),
    ]
