# Generated by Django 4.2.11 on 2026-07-13 15:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def popular_tributos_iniciais(apps, schema_editor):
    Empresa = apps.get_model('cadastros', 'Empresa')
    Tributo = apps.get_model('fiscal', 'Tributo')
    tributos = [
        ("ICMS", "Imposto sobre Circulação de Mercadorias e Serviços", "ESTADUAL", True, "Tributo atual sobre circulação de mercadorias."),
        ("ICMS_ST", "ICMS por Substituição Tributária", "ESTADUAL", True, "Usado em operações sujeitas a substituição tributária."),
        ("FCP", "Fundo de Combate à Pobreza", "ESTADUAL", True, "Adicional estadual em operações específicas."),
        ("PIS", "Programa de Integração Social", "FEDERAL", True, "Tributo federal atual sobre receita."),
        ("COFINS", "Contribuição para o Financiamento da Seguridade Social", "FEDERAL", True, "Tributo federal atual sobre receita."),
        ("CSLL", "Contribuição Social sobre o Lucro Líquido", "FEDERAL", True, "Tributo sobre lucro, tratado gerencialmente em apurações."),
        ("IRPJ", "Imposto de Renda Pessoa Jurídica", "FEDERAL", True, "Tributo sobre lucro, tratado gerencialmente em apurações."),
        ("IPI", "Imposto sobre Produtos Industrializados", "FEDERAL", True, "Mantido para operações industriais ou futuras necessidades."),
        ("II", "Imposto de Importação", "FEDERAL", True, "Mantido para compras/importações futuras."),
        ("CBS", "Contribuição sobre Bens e Serviços", "FEDERAL", False, "Tributo da reforma tributária em transição."),
        ("IBS", "Imposto sobre Bens e Serviços", "ESTADUAL", False, "Tributo da reforma tributária em transição."),
        ("IS", "Imposto Seletivo", "FEDERAL", False, "Tributo seletivo da reforma tributária."),
    ]
    for empresa in Empresa.objects.all():
        for codigo, descricao, esfera, atual, observacoes in tributos:
            Tributo.objects.update_or_create(
                empresa=empresa,
                codigo=codigo,
                defaults={
                    "descricao": descricao,
                    "esfera": esfera,
                    "atual": atual,
                    "ativo": True,
                    "observacoes": observacoes,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0026_popula_ncms_insumo_uso_consumo'),
        ('cadastros', '0016_empresa_licenca_master_empresa_usa_compras_and_more'),
        ('fiscal', '0011_popula_cfops_compra_insumo_uso_consumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('descricao', models.CharField(max_length=120)),
                ('esfera', models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], db_index=True, default='FEDERAL', max_length=12)),
                ('atual', models.BooleanField(db_index=True, default=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tributos', to='cadastros.empresa')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegraTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('tipo_operacao', models.CharField(db_index=True, default='VENDA', max_length=20)),
                ('regime_tributario', models.CharField(choices=[('TODOS', 'Todos'), ('SIMPLES', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real')], db_index=True, default='TODOS', max_length=20)),
                ('tipo_produto', models.CharField(choices=[('TODOS', 'Todos'), ('REVENDA', 'Revenda'), ('USO_CONSUMO', 'Uso/Consumo'), ('INSUMO', 'Insumo'), ('PROPRIO', 'Produto próprio')], db_index=True, default='TODOS', max_length=20)),
                ('uf_origem', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('uf_destino', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('cst_csosn', models.CharField(blank=True, max_length=4, null=True)),
                ('base_calculo', models.CharField(choices=[('VALOR_ITEM', 'Valor do item'), ('VALOR_TOTAL', 'Valor total')], default='VALOR_ITEM', max_length=20)),
                ('aliquota', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reducao_base', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('permite_credito', models.BooleanField(default=False)),
                ('compoe_custo', models.BooleanField(default=False)),
                ('entra_dre', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('vigencia_inicio', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cfop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_tributarias', to='fiscal.cfop')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_tributarias', to='cadastros.empresa')),
                ('ncm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_tributarias', to='produto.ncm')),
                ('tributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras', to='fiscal.tributo')),
            ],
            options={
                'ordering': ['nome', 'tributo__codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='tributo',
            index=models.Index(fields=['empresa', 'codigo'], name='fiscal_trib_empresa_08136b_idx'),
        ),
        migrations.AddIndex(
            model_name='tributo',
            index=models.Index(fields=['ativo'], name='fiscal_trib_ativo_aee5ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='tributo',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_tributo_empresa_codigo'),
        ),
        migrations.AddIndex(
            model_name='regratributaria',
            index=models.Index(fields=['empresa', 'ativo'], name='fiscal_regr_empresa_46da4b_idx'),
        ),
        migrations.AddIndex(
            model_name='regratributaria',
            index=models.Index(fields=['tipo_operacao', 'regime_tributario'], name='fiscal_regr_tipo_op_3530f6_idx'),
        ),
        migrations.AddIndex(
            model_name='regratributaria',
            index=models.Index(fields=['uf_origem', 'uf_destino'], name='fiscal_regr_uf_orig_565c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='regratributaria',
            index=models.Index(fields=['vigencia_inicio', 'vigencia_fim'], name='fiscal_regr_vigenci_5dd65e_idx'),
        ),
        migrations.RunPython(popular_tributos_iniciais, migrations.RunPython.noop),
    ]
