# Generated by Django 4.2.11 on 2026-07-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0014_notafiscalsaida_notafiscalsaidaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalsaida',
            name='autorizada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='protocolo_autorizacao',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='xml',
            field=models.TextField(blank=True, default=''),
        ),
    ]
