# Generated by Django 4.2.11 on 2026-08-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0017_nfe_entrada_pedido_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalentrada',
            name='destinatario_documento',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='destinatario_nome',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='emitente_documento',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='emitente_ie',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='emitente_nome',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='natureza_operacao',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='protocolo_autorizacao',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='xml_importado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='xml_original',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='NotaFiscalEntradaItemXml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('codigo_produto_fornecedor', models.CharField(blank=True, default='', max_length=80)),
                ('descricao_produto', models.CharField(blank=True, default='', max_length=255)),
                ('gtin_ean', models.CharField(blank=True, default='', max_length=14)),
                ('ncm', models.CharField(blank=True, default='', max_length=10)),
                ('cfop', models.CharField(blank=True, default='', max_length=4)),
                ('unidade_comercial', models.CharField(blank=True, default='', max_length=20)),
                ('quantidade_comercial', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('valor_unitario_comercial', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('valor_produto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('informacoes_adicionais', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_xml', to='fiscal.notafiscalentrada')),
            ],
            options={
                'db_table': 'fiscal_nota_fiscal_entrada_item_xml',
                'indexes': [models.Index(fields=['nota', 'codigo_produto_fornecedor'], name='ix_fiscal_nfe_xml_cod'), models.Index(fields=['gtin_ean'], name='ix_fiscal_nfe_xml_gtin')],
            },
        ),
        migrations.AddConstraint(
            model_name='notafiscalentradaitemxml',
            constraint=models.UniqueConstraint(fields=('nota', 'numero_item'), name='uq_fiscal_nfe_xml_item_numero'),
        ),
    ]
