# Generated by Django 4.2.11 on 2026-08-26 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0034_produto_fornecedor_conversao_unidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscal', '0018_nfe_entrada_xml_importacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='conciliado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='conciliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_xml_nfe_conciliados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='origem_conciliacao',
            field=models.CharField(blank=True, choices=[('VINCULO', 'Vínculo existente'), ('PEDIDO', 'Pedido'), ('GTIN', 'GTIN/EAN'), ('MANUAL', 'Manual')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_xml_nfe', to='produto.produto'),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='produto_fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_xml_nfe', to='produto.produtofornecedor'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentradaitemxml',
            index=models.Index(fields=['nota', 'produto'], name='ix_fiscal_nfe_xml_prod'),
        ),
    ]
