# Generated by Django 4.2.11 on 2026-08-26 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0034_produto_fornecedor_conversao_unidade'),
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscal', '0019_nfe_xml_conciliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='conferido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='conferido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_xml_nfe_conferidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='quantidade_recebida',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='NotaFiscalEntradaDivergenciaXml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_fiscal', models.DecimalField(decimal_places=6, max_digits=18)),
                ('quantidade_recebida', models.DecimalField(decimal_places=6, max_digits=18)),
                ('quantidade_faltante', models.DecimalField(decimal_places=6, max_digits=18)),
                ('valor_divergente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDA', 'Resolvida')], db_index=True, default='PENDENTE', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divergencias_nfe_xml_conferidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divergencias_nfe_xml', to='cadastros.empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divergencias_nfe_xml', to='cadastros.fornecedor')),
                ('item_xml', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='divergencia', to='fiscal.notafiscalentradaitemxml')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias_xml', to='fiscal.notafiscalentrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divergencias_nfe_xml', to='produto.produto')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divergencias_nfe_xml_resolvidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fiscal_nota_fiscal_entrada_divergencia_xml',
                'indexes': [models.Index(fields=['nota', 'status'], name='ix_fiscal_nfe_div_xml_st'), models.Index(fields=['empresa', 'status'], name='ix_fiscal_nfe_div_emp_st')],
            },
        ),
    ]
