# Generated by Django 4.2.11 on 2026-08-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0028_cotacaoitem_ordem_servico_material_origem_and_more'),
        ('fiscal', '0020_nfe_xml_conferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='efetivado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='fator_conversao_efetivado',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='pedido_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_xml_nfe', to='compras.pedidocompraitem'),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='quantidade_interna_efetivada',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='unidade_fornecedor_efetivada',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
