# Generated by Django 4.2.11 on 2026-08-26 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscal', '0021_nfe_xml_efetivacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalentrada',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nfe_entrada_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notafiscalentradadivergenciaxml',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDA', 'Resolvida'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=10),
        ),
    ]
