# Generated by Django 4.2.11 on 2026-08-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        ('fiscal', '0022_notafiscalentrada_cancelado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalEntradaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(db_index=True, max_length=44)),
                ('id_evento', models.CharField(blank=True, default='', max_length=80)),
                ('tipo_evento', models.CharField(db_index=True, max_length=10)),
                ('tipo_evento_descricao', models.CharField(blank=True, default='', max_length=120)),
                ('sequencia', models.PositiveIntegerField(default=1)),
                ('data_hora_evento', models.DateTimeField(blank=True, null=True)),
                ('protocolo', models.CharField(blank=True, default='', max_length=30)),
                ('cstat', models.CharField(blank=True, db_index=True, default='', max_length=4)),
                ('xmotivo', models.CharField(blank=True, default='', max_length=255)),
                ('ambiente', models.CharField(blank=True, db_index=True, default='', max_length=1)),
                ('origem', models.CharField(choices=[('IMPORTACAO_MANUAL', 'Importação manual'), ('CONSULTA_SEFAZ', 'Consulta SEFAZ'), ('TRANSMISSAO_FUTURA', 'Transmissão futura')], default='IMPORTACAO_MANUAL', max_length=30)),
                ('situacao_processamento', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('PROCESSADO', 'Processado'), ('REJEITADO', 'Rejeitado')], default='REGISTRADO', max_length=20)),
                ('xml_original', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fiscal_nota_fiscal_entrada_evento',
            },
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='ambiente',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='cobranca_fiscal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='codigo_numerico',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='codigo_uf',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='consumidor_final',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='dh_emissao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='dh_saida_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='digito_verificador',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='documentos_referenciados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='finalidade_nfe',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='identificador_destino',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='informacoes_complementares_contribuinte',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='informacoes_complementares_fisco',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='intermediador',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='municipio_fato_gerador',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='nfe_id_xml',
            field=models.CharField(blank=True, default='', max_length=47),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='pagamentos_fiscais',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='presenca_comprador',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='processo_emissao',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='protocolo_chave_acesso',
            field=models.CharField(blank=True, default='', max_length=44),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='protocolo_cstat',
            field=models.CharField(blank=True, db_index=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='protocolo_motivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='protocolo_recebido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='situacao_fiscal',
            field=models.CharField(choices=[('DESCONHECIDA', 'Desconhecida'), ('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('DENEGADA', 'Denegada')], db_index=True, default='DESCONHECIDA', max_length=20),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='tipo_emissao',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='tipo_impressao',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='tipo_operacao',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='totais_fiscais',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='versao_leiaute',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='versao_processo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='notafiscalentradaitemxml',
            name='impostos_fiscais',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['empresa', 'situacao_fiscal'], name='ix_fiscal_nfe_emp_sitfis'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['empresa', 'ambiente'], name='ix_fiscal_nfe_emp_amb'),
        ),
        migrations.AddField(
            model_name='notafiscalentradaevento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_nfe_entrada', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='notafiscalentradaevento',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_fiscais', to='fiscal.notafiscalentrada'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentradaevento',
            index=models.Index(fields=['nota', 'tipo_evento', 'sequencia'], name='ix_fiscal_nfe_evt_tipo_seq'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentradaevento',
            index=models.Index(fields=['empresa', 'ambiente', 'tipo_evento'], name='ix_fiscal_nfe_evt_emp_amb'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalentradaevento',
            constraint=models.UniqueConstraint(fields=('empresa', 'chave_acesso', 'tipo_evento', 'sequencia', 'protocolo'), name='uq_fiscal_nfe_evento_idem'),
        ),
    ]
