# Generated by Django 4.2.11 on 2026-08-26 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        ('financeiro', '0026_nfe_xml_efetivacao'),
        ('fiscal', '0023_notafiscalentradaevento_notafiscalentrada_ambiente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamentoFiscalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tpag', models.CharField(db_index=True, max_length=2)),
                ('descricao_fiscal', models.CharField(blank=True, default='', max_length=80)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formas_pagamento_fiscais_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento_fiscais', to='cadastros.empresa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapas_fiscais_nfe', to='financeiro.formapagamento')),
            ],
            options={
                'db_table': 'fiscal_forma_pagamento_fiscal_map',
                'indexes': [models.Index(fields=['empresa', 'codigo_tpag', 'ativo'], name='ix_fiscal_tpag_emp_cod_atv')],
            },
        ),
        migrations.AddConstraint(
            model_name='formapagamentofiscalmap',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_tpag'), name='uq_fiscal_tpag_empresa'),
        ),
    ]
