# Generated by Django 4.2.11 on 2026-09-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_centrocusto'),
        ('fiscal', '0024_formapagamentofiscalmap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlFornecedorRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(db_index=True, max_length=44, unique=True)),
                ('modelo', models.CharField(default='55', max_length=2)),
                ('serie', models.CharField(blank=True, default='', max_length=10)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('dh_emissao', models.DateTimeField(blank=True, null=True)),
                ('emitente_documento', models.CharField(blank=True, default='', max_length=14)),
                ('emitente_nome', models.CharField(blank=True, default='', max_length=120)),
                ('destinatario_documento', models.CharField(blank=True, default='', max_length=14)),
                ('destinatario_nome', models.CharField(blank=True, default='', max_length=120)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('situacao_fiscal', models.CharField(choices=[('DESCONHECIDA', 'Desconhecida'), ('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('DENEGADA', 'Denegada')], db_index=True, default='DESCONHECIDA', max_length=20)),
                ('status_operacional', models.CharField(choices=[('DETECTADO', 'Detectado'), ('AGUARDANDO_RECEBIMENTO', 'Aguardando recebimento'), ('EM_RECEBIMENTO', 'Em recebimento'), ('RECEBIDO', 'Recebido'), ('PROCESSADO', 'Processado'), ('IGNORADO', 'Ignorado')], db_index=True, default='DETECTADO', max_length=24)),
                ('caminho_origem_local', models.CharField(blank=True, default='', max_length=500)),
                ('identificador_agente', models.CharField(blank=True, default='', max_length=120)),
                ('detectado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('erro_processamento', models.TextField(blank=True, default='')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xmls_fornecedor_recebidos', to='cadastros.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xmls_fornecedor_recebidos', to='cadastros.fornecedor')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xmls_fornecedor_recebidos', to='cadastros.loja')),
            ],
            options={
                'db_table': 'fiscal_xml_fornecedor_recebido',
                'ordering': ['-detectado_em', '-id'],
                'indexes': [models.Index(fields=['empresa', 'status_operacional'], name='ix_xml_forn_emp_status'), models.Index(fields=['empresa', 'situacao_fiscal'], name='ix_xml_forn_emp_sitfis'), models.Index(fields=['emitente_documento'], name='ix_xml_forn_emit_doc'), models.Index(fields=['destinatario_documento'], name='ix_xml_forn_dest_doc')],
            },
        ),
    ]
