# Generated by Django 4.2.11 on 2026-09-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_centrocusto'),
        ('fiscal', '0025_xml_fornecedor_recebido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoXmlFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_local', models.CharField(max_length=500)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('identificador_agente', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_xml_fornecedor', to='cadastros.empresa')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_xml_fornecedor', to='cadastros.loja')),
            ],
            options={
                'db_table': 'fiscal_configuracao_xml_fornecedor',
                'ordering': ['empresa_id', 'loja_id', 'caminho_local'],
                'indexes': [models.Index(fields=['empresa', 'loja', 'ativo'], name='ix_cfg_xml_forn_emp_loja_atv'), models.Index(fields=['identificador_agente'], name='ix_cfg_xml_forn_agente')],
            },
        ),
        migrations.AddConstraint(
            model_name='configuracaoxmlfornecedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'loja', 'caminho_local'), name='uq_config_xml_forn_emp_loja_path'),
        ),
    ]
