# Generated by Django 4.2.11 on 2026-09-02 23:01

from django.db import migrations, models


def preencher_loja_escopo_unicidade(apps, schema_editor):
    ConfiguracaoXmlFornecedor = apps.get_model("fiscal", "ConfiguracaoXmlFornecedor")
    for config in ConfiguracaoXmlFornecedor.objects.all().only("id", "loja_id"):
        ConfiguracaoXmlFornecedor.objects.filter(pk=config.pk).update(loja_escopo_unicidade=config.loja_id or 0)


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0026_configuracaoxmlfornecedor_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='configuracaoxmlfornecedor',
            name='uq_config_xml_forn_emp_loja_path',
        ),
        migrations.AddField(
            model_name='configuracaoxmlfornecedor',
            name='loja_escopo_unicidade',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(preencher_loja_escopo_unicidade, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='configuracaoxmlfornecedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'loja_escopo_unicidade', 'caminho_local'), name='uq_cfg_xml_forn_emp_scope_path'),
        ),
    ]
