# Generated by Django 4.2.11 on 2026-09-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_centrocusto'),
        ('fiscal', '0027_remove_configuracaoxmlfornecedor_uq_config_xml_forn_emp_loja_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteLocalSysvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=120)),
                ('nome', models.CharField(max_length=120)),
                ('token_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('token_prefixo', models.CharField(blank=True, default='', max_length=12)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('ultimo_contato', models.DateTimeField(blank=True, null=True)),
                ('versao', models.CharField(blank=True, default='', max_length=40)),
                ('hostname', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentes_locais_sysvar', to='cadastros.empresa')),
            ],
            options={
                'db_table': 'fiscal_agente_local_sysvar',
                'ordering': ['empresa_id', 'identificador'],
                'indexes': [models.Index(fields=['empresa', 'ativo'], name='ix_agente_local_emp_ativo'), models.Index(fields=['token_hash'], name='ix_agente_local_token_hash')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentelocalsysvar',
            constraint=models.UniqueConstraint(fields=('empresa', 'identificador'), name='uq_agente_local_sysvar_empresa_ident'),
        ),
    ]
