# Generated by Django 4.2.11 on 2026-09-03 12:06

from django.db import migrations, models


def blank_token_hash_to_null(apps, schema_editor):
    AgenteLocalSysvar = apps.get_model("fiscal", "AgenteLocalSysvar")
    AgenteLocalSysvar.objects.filter(token_hash="").update(token_hash=None)


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0028_agentelocalsysvar_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agentelocalsysvar',
            name='ix_agente_local_token_hash',
        ),
        migrations.RunPython(blank_token_hash_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='agentelocalsysvar',
            name='token_hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
