# Generated by Django 4.2.11 on 2026-09-03 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0029_centrocusto'),
        ('fiscal', '0029_remove_agentelocalsysvar_ix_agente_local_token_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtivacaoAgenteLocalSysvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('codigo_prefixo', models.CharField(db_index=True, max_length=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(db_index=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativacoes', to='fiscal.agentelocalsysvar')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativacoes_agente_local_sysvar', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativacoes_agente_local_sysvar', to='cadastros.empresa')),
            ],
            options={
                'db_table': 'fiscal_ativacao_agente_local_sysvar',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'codigo_prefixo'], name='ix_ativ_ag_local_emp_pref'), models.Index(fields=['expira_em', 'usado_em'], name='ix_ativ_ag_local_exp_uso')],
            },
        ),
    ]
