# Generated by Django 4.2.11 on 2026-09-04 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0029_requisicaosetor_centro_custo'),
        ('cadastros', '0029_centrocusto'),
        ('fiscal', '0030_ativacaoagentelocalsysvar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoMercadoriaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_fornecedor_ativo_key', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_CONFERENCIA', 'Em conferência'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='ABERTO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_mercadoria_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_mercadoria', to='cadastros.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_mercadoria', to='cadastros.fornecedor')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_mercadoria', to='cadastros.loja')),
                ('xml_fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_mercadoria', to='fiscal.xmlfornecedorrecebido')),
            ],
            options={
                'db_table': 'fiscal_recebimento_mercadoria_estoque',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecebimentoMercadoriaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_mercadoria', to='compras.pedidocompra')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_vinculados', to='fiscal.recebimentomercadoriaestoque')),
            ],
            options={
                'db_table': 'fiscal_recebimento_mercadoria_pedido',
                'ordering': ['pedido_id'],
                'indexes': [models.Index(fields=['recebimento'], name='ix_receb_merc_ped_receb'), models.Index(fields=['pedido'], name='ix_receb_merc_ped_pedido')],
            },
        ),
        migrations.AddConstraint(
            model_name='recebimentomercadoriapedido',
            constraint=models.UniqueConstraint(fields=('recebimento', 'pedido'), name='uq_receb_merc_pedido'),
        ),
        migrations.AddIndex(
            model_name='recebimentomercadoriaestoque',
            index=models.Index(fields=['empresa', 'status'], name='ix_receb_merc_emp_status'),
        ),
        migrations.AddIndex(
            model_name='recebimentomercadoriaestoque',
            index=models.Index(fields=['empresa', 'loja'], name='ix_receb_merc_emp_loja'),
        ),
        migrations.AddIndex(
            model_name='recebimentomercadoriaestoque',
            index=models.Index(fields=['empresa', 'fornecedor'], name='ix_receb_merc_emp_forn'),
        ),
        migrations.AddConstraint(
            model_name='recebimentomercadoriaestoque',
            constraint=models.UniqueConstraint(fields=('empresa', 'xml_fornecedor_ativo_key'), name='uq_receb_merc_xml_ativo'),
        ),
    ]
