# Generated by Django 4.2.11 on 2026-09-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0029_requisicaosetor_centro_custo'),
        ('produto', '0035_estoquemovimentacao_origem'),
        ('fiscal', '0031_recebimentomercadoriaestoque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoMercadoriaConferenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_esperada', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantidade_recebida', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_conferencia', to='produto.cor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_conferencia', to='compras.pedidocompra')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_conferencia', to='compras.pedidocompraitem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_conferencia', to='produto.produto')),
                ('produto_detalhe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_conferencia', to='produto.produtodetalhe')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencia_itens', to='fiscal.recebimentomercadoriaestoque')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_conferencia', to='produto.tamanho')),
            ],
            options={
                'db_table': 'fiscal_recebimento_mercadoria_conferencia_item',
                'ordering': ['produto__referencia', 'cor__Descricao', 'tamanho__idgrade_id', 'tamanho__Idtamanho', 'id'],
                'indexes': [models.Index(fields=['recebimento'], name='ix_receb_conf_receb'), models.Index(fields=['pedido'], name='ix_receb_conf_pedido'), models.Index(fields=['pedido_item'], name='ix_receb_conf_peditem'), models.Index(fields=['produto', 'cor', 'tamanho'], name='ix_receb_conf_sku_base')],
            },
        ),
        migrations.AddConstraint(
            model_name='recebimentomercadoriaconferenciaitem',
            constraint=models.UniqueConstraint(fields=('recebimento', 'pedido_item', 'tamanho'), name='uq_receb_conf_item_tamanho'),
        ),
    ]
