# Generated by Codex on 2026-09-20

from django.db import migrations, models
import django.db.models.deletion


def preencher_loja_nfce(apps, schema_editor):
    NFCe = apps.get_model("fiscal", "NFCe")
    for nfce in NFCe.objects.select_related("venda").filter(loja__isnull=True).iterator():
        nfce.loja_id = nfce.venda.loja_id
        nfce.save(update_fields=["loja"])


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0029_centrocusto"),
        ("fiscal", "0039_notafiscalentrada_xml_fornecedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfce",
            name="loja",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="nfces", to="cadastros.loja"),
        ),
        migrations.AddField(
            model_name="nfce",
            name="tipo_emissao",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="nfce",
            name="qr_code_payload",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="nfce",
            name="emitida_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nfce",
            name="entrada_contingencia_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nfce",
            name="justificativa_contingencia",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="nfce",
            name="status",
            field=models.CharField(
                choices=[
                    ("DIGITADA", "Digitada"),
                    ("EMITINDO", "Emitindo"),
                    ("GERADA", "Gerada"),
                    ("PENDENTE_TRANSMISSAO", "Pendente transmissao"),
                    ("AUTORIZADA", "Autorizada"),
                    ("REJEITADA", "Rejeitada"),
                    ("ERRO_GERACAO", "Erro geracao"),
                    ("CONTINGENCIA", "Contingencia"),
                    ("CANCELADA", "Cancelada"),
                ],
                db_index=True,
                default="DIGITADA",
                max_length=24,
            ),
        ),
        migrations.RunPython(preencher_loja_nfce, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="nfce",
            name="uq_nfce_serie_numero",
        ),
        migrations.AlterField(
            model_name="nfce",
            name="loja",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="nfces", to="cadastros.loja"),
        ),
        migrations.AddConstraint(
            model_name="nfce",
            constraint=models.UniqueConstraint(fields=("loja", "ambiente", "modelo", "serie", "numero"), name="uq_nfce_loja_amb_mod_serie_num"),
        ),
    ]
