# Generated by Django 4.2.11 on 2025-11-04 19:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('Idcodigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('colecao', models.CharField(default='00', max_length=2)),
                ('estacao', models.CharField(default='00', max_length=2)),
                ('valor_var', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('Idcolecao', models.BigAutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('Codigo', models.CharField(blank=True, help_text='Dois ultimos digitos do ano, ex.: 2026 = 26', max_length=2, null=True)),
                ('Estacao', models.CharField(blank=True, choices=[('01', 'Verão'), ('02', 'Outono'), ('03', 'Inverno'), ('04', 'Primavera')], max_length=2, null=True)),
                ('Status', models.CharField(blank=True, choices=[('CR', 'Criação'), ('PD', 'Produção'), ('AT', 'Ativa'), ('EN', 'Encerrada'), ('AR', 'Arquivada')], max_length=10, null=True)),
                ('Contador', models.IntegerField(blank=True, default=0, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigEan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_prefix', models.CharField(default='789', help_text='Prefixo do país (fixo 789).', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Use exatamente 3 dígitos.')])),
                ('company_prefix', models.CharField(help_text='Prefixo da empresa (4 dígitos).', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Use exatamente 4 dígitos.')])),
                ('next_itemref', models.PositiveIntegerField(default=1, help_text='Sequência 00001..99999 do item para este prefixo')),
                ('ativo', models.BooleanField(default=True, help_text='Se marcado, este prefixo pode gerar novos SKUs')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração EAN',
                'verbose_name_plural': 'Configuração EAN',
                'db_table': 'config_ean',
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('Idcor', models.BigAutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('Codigo', models.CharField(blank=True, max_length=12, null=True)),
                ('Cor', models.CharField(max_length=30)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('Idestoque', models.BigAutoField(primary_key=True, serialize=False)),
                ('CodigodeBarra', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'EAN-13 deve ter exatamente 13 dígitos.')])),
                ('referencia', models.CharField(default='', max_length=30)),
                ('Estoque', models.IntegerField(blank=True, null=True)),
                ('reserva', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('Idgrade', models.BigAutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('Idgrupo', models.BigAutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=12)),
                ('CodigoRef', models.CharField(default='01', help_text='2 dígitosntaõ  ex.: 01', max_length=2)),
                ('Descricao', models.CharField(max_length=100)),
                ('Margem', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('Idmaterial', models.BigAutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('Codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ncm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'NCM deve ter exatamente 8 dígitos.')])),
                ('descricao', models.CharField(max_length=1000)),
                ('aliquota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('campo1', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packs', to='produto.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('Idproduto', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_produto', models.CharField(choices=[('1', 'Revenda'), ('2', 'Uso/Consumo')], default='1', max_length=1)),
                ('referencia', models.CharField(blank=True, help_text='Gerada automaticamente: AA-BB-CCDDD', max_length=11, null=True, unique=True)),
                ('descricao', models.CharField(max_length=120)),
                ('descricao_reduzida', models.CharField(blank=True, max_length=60, null=True)),
                ('ncm', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'NCM deve ter exatamente 8 dígitos.')])),
                ('origem_mercadoria', models.PositiveSmallIntegerField(blank=True, help_text='0=nacional, etc.', null=True)),
                ('csosn_ou_cst_icms', models.CharField(blank=True, max_length=3, null=True)),
                ('aliquota_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cfop_venda_dentro', models.CharField(blank=True, max_length=4, null=True)),
                ('cfop_venda_fora', models.CharField(blank=True, max_length=4, null=True)),
                ('cst_pis', models.CharField(blank=True, max_length=2, null=True)),
                ('aliq_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cst_cofins', models.CharField(blank=True, max_length=2, null=True)),
                ('aliq_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ipi_situacao', models.CharField(blank=True, max_length=2, null=True)),
                ('aliq_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inativo', models.DateTimeField(blank=True, null=True)),
                ('colecao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.colecao')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produto.grade')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.grupo')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.material')),
            ],
        ),
        migrations.CreateModel(
            name='Tabelapreco',
            fields=[
                ('Idtabela', models.BigAutoField(primary_key=True, serialize=False)),
                ('NomeTabela', models.CharField(default='Tabela', max_length=100)),
                ('DataInicio', models.DateField()),
                ('Promocao', models.BooleanField(default=False)),
                ('DataFim', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('Idunidade', models.BigAutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('Codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('Idtamanho', models.BigAutoField(primary_key=True, serialize=False)),
                ('Tamanho', models.CharField(max_length=10)),
                ('Descricao', models.CharField(default='Tamanho', max_length=100)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('idgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.grade')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaprecoProduto',
            fields=[
                ('Idprodutopreco', models.BigAutoField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=4, max_digits=12)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('DataInicio', models.DateField(default=django.utils.timezone.now)),
                ('DataFim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='produto.produto')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precos', to='produto.tabelapreco')),
            ],
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('Idsubgrupo', models.BigAutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('Margem', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Idgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoDetalhe',
            fields=[
                ('IdprodutoDetalhe', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_item_ref', models.CharField(help_text='Sequência 00001..99999 por prefixo para compor o EAN-13.', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Use exatamente 5 dígitos.')])),
                ('ean13', models.CharField(help_text='EAN-13 (789 + empresa(4) + item(5) + DV).', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'EAN-13 deve ter exatamente 13 dígitos.')])),
                ('ativo', models.BooleanField(default=True)),
                ('config_ean', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='produto.configean')),
                ('idcor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.cor')),
                ('idtamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.tamanho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='produto.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.subgrupo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.unidade'),
        ),
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produto.pack')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packs_itens', to='produto.tamanho')),
            ],
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['Codigo'], name='produto_gru_Codigo_701120_idx'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='Idloja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.loja'),
        ),
        migrations.AddIndex(
            model_name='cor',
            index=models.Index(fields=['Codigo'], name='produto_cor_Codigo_4c74c4_idx'),
        ),
        migrations.AddIndex(
            model_name='configean',
            index=models.Index(fields=['ativo'], name='config_ean_ativo_2c79aa_idx'),
        ),
        migrations.AddIndex(
            model_name='configean',
            index=models.Index(fields=['company_prefix'], name='config_ean_company_713e88_idx'),
        ),
        migrations.AddConstraint(
            model_name='configean',
            constraint=models.UniqueConstraint(fields=('country_prefix', 'company_prefix'), name='uq_country_company_prefix'),
        ),
        migrations.AddConstraint(
            model_name='colecao',
            constraint=models.UniqueConstraint(fields=('Codigo', 'Estacao'), name='uq_colecao_codigo_estacao'),
        ),
        migrations.AddConstraint(
            model_name='codigos',
            constraint=models.UniqueConstraint(fields=('colecao', 'estacao'), name='unique_colecao_estacao'),
        ),
        migrations.AddIndex(
            model_name='tabelaprecoproduto',
            index=models.Index(fields=['produto', 'tabela'], name='produto_tab_produto_060670_idx'),
        ),
        migrations.AddIndex(
            model_name='tabelaprecoproduto',
            index=models.Index(fields=['DataInicio', 'DataFim'], name='produto_tab_DataIni_8576d0_idx'),
        ),
        migrations.AddIndex(
            model_name='produtodetalhe',
            index=models.Index(fields=['ean13'], name='produto_pro_ean13_c569c0_idx'),
        ),
        migrations.AddIndex(
            model_name='produtodetalhe',
            index=models.Index(fields=['codigo_item_ref'], name='produto_pro_codigo__6563f7_idx'),
        ),
        migrations.AddIndex(
            model_name='produtodetalhe',
            index=models.Index(fields=['config_ean'], name='produto_pro_config__fb3877_idx'),
        ),
        migrations.AddConstraint(
            model_name='produtodetalhe',
            constraint=models.UniqueConstraint(fields=('produto', 'idcor', 'idtamanho'), name='uq_produto_cor_tamanho'),
        ),
        migrations.AddConstraint(
            model_name='produtodetalhe',
            constraint=models.UniqueConstraint(fields=('config_ean', 'codigo_item_ref'), name='uq_prefixo_itemref'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tipo_produto'], name='produto_pro_tipo_pr_81dbe3_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ncm'], name='produto_pro_ncm_56381d_idx'),
        ),
        migrations.AddIndex(
            model_name='packitem',
            index=models.Index(fields=['pack'], name='ix_packitem_pack'),
        ),
        migrations.AddIndex(
            model_name='packitem',
            index=models.Index(fields=['tamanho'], name='ix_packitem_tamanho'),
        ),
        migrations.AddConstraint(
            model_name='packitem',
            constraint=models.UniqueConstraint(fields=('pack', 'tamanho'), name='uq_packitem_pack_tamanho'),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['grade'], name='ix_pack_grade'),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['ativo'], name='ix_pack_ativo'),
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(fields=('grade', 'nome'), name='uq_pack_grade_nome'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['CodigodeBarra'], name='produto_est_Codigod_a00da4_idx'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['Idloja'], name='produto_est_Idloja__d458d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.UniqueConstraint(fields=('CodigodeBarra', 'Idloja'), name='uq_estoque_codigodebarra_loja'),
        ),
    ]
