# Generated by Django 4.2.11 on 2025-11-04 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_ncm_ncm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='ncm',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'NCM deve ter exatamente 10 dígitos.')]),
        ),
    ]
