# Generated by Django 4.2.11 on 2025-11-05 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_ncm_ncm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}\\.\\d{2}\\.\\d{2}$', 'NCM deve estar no formato ####.##.##')]),
        ),
    ]
