# Generated by Django 4.2.11 on 2025-11-05 14:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_ncm'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='bloqueado_venda',
            field=models.BooleanField(default=False, help_text='Se marcado, impede operações de venda para este produto.'),
        ),
        migrations.AddField(
            model_name='produtodetalhe',
            name='bloqueado_venda',
            field=models.BooleanField(default=False, help_text='Se marcado, impede operações de venda para este SKU.'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='CodigoRef',
            field=models.CharField(default='01', help_text='2 dígitos, ex.: 01', max_length=2),
        ),
        migrations.AlterField(
            model_name='produtodetalhe',
            name='codigo_item_ref',
            field=models.CharField(blank=True, help_text='Sequência 00001..99999 por prefixo para compor o EAN-13.', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Use exatamente 5 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='produtodetalhe',
            name='config_ean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='produto.configean'),
        ),
        migrations.AlterField(
            model_name='produtodetalhe',
            name='ean13',
            field=models.CharField(blank=True, editable=False, help_text='EAN-13 (789 + empresa(4) + item(5) + DV).', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'EAN-13 deve ter exatamente 13 dígitos.')]),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ativo'], name='produto_pro_ativo_146c98_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['bloqueado_venda'], name='produto_pro_bloquea_f44f02_idx'),
        ),
        migrations.AddIndex(
            model_name='produtodetalhe',
            index=models.Index(fields=['ativo'], name='produto_pro_ativo_467d32_idx'),
        ),
        migrations.AddIndex(
            model_name='produtodetalhe',
            index=models.Index(fields=['bloqueado_venda'], name='produto_pro_bloquea_fed4b8_idx'),
        ),
    ]
