# Generated by Django 4.2.11 on 2026-05-29 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_loja_contacontabil_loja_dataabertura_and_more'),
        ('produto', '0006_produto_bloqueado_venda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioEstoque',
            fields=[
                ('Idinventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('CANCELADO', 'Cancelado')], db_index=True, default='ABERTO', max_length=10)),
                ('data_abertura', models.DateField(default=django.utils.timezone.now)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Idloja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.loja')),
            ],
            options={
                'db_table': 'produto_inventario_estoque',
                'ordering': ['-data_abertura', '-Idinventario'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueMovimentacao',
            fields=[
                ('Idmovimento', models.BigAutoField(primary_key=True, serialize=False)),
                ('CodigodeBarra', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'EAN-13 deve ter exatamente 13 dígitos.')])),
                ('referencia', models.CharField(db_index=True, default='', max_length=30)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('RESERVA', 'Reserva')], db_index=True, max_length=10)),
                ('quantidade', models.IntegerField()),
                ('saldo_anterior', models.IntegerField(default=0)),
                ('saldo_posterior', models.IntegerField(default=0)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_movimento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('Idloja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.loja')),
            ],
            options={
                'db_table': 'produto_estoque_movimentacao',
                'ordering': ['-data_movimento', '-Idmovimento'],
            },
        ),
        migrations.CreateModel(
            name='InventarioEstoqueItem',
            fields=[
                ('Idinventarioitem', models.BigAutoField(primary_key=True, serialize=False)),
                ('CodigodeBarra', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'EAN-13 deve ter exatamente 13 dígitos.')])),
                ('referencia', models.CharField(default='', max_length=30)),
                ('saldo_sistema', models.IntegerField(default=0)),
                ('saldo_contado', models.IntegerField(default=0)),
                ('diferenca', models.IntegerField(default=0)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produto.inventarioestoque')),
            ],
            options={
                'db_table': 'produto_inventario_estoque_item',
                'indexes': [models.Index(fields=['inventario'], name='produto_inv_inventa_fdbe1a_idx'), models.Index(fields=['CodigodeBarra'], name='produto_inv_Codigod_6cda57_idx'), models.Index(fields=['referencia'], name='produto_inv_referen_877292_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventarioestoqueitem',
            constraint=models.UniqueConstraint(fields=('inventario', 'CodigodeBarra'), name='uq_inventario_item_ean'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimentacao',
            index=models.Index(fields=['Idloja', 'CodigodeBarra'], name='produto_est_Idloja__a6fff1_idx'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimentacao',
            index=models.Index(fields=['referencia'], name='produto_est_referen_aeb0be_idx'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimentacao',
            index=models.Index(fields=['tipo', 'data_movimento'], name='produto_est_tipo_40d1e7_idx'),
        ),
    ]
