# Generated by Django 4.2.11 on 2026-07-05 13:29

from django.db import migrations, models
import django.db.models.deletion


def separar_auxiliares_por_empresa(apps, schema_editor):
    Empresa = apps.get_model('cadastros', 'Empresa')
    ConfigEan = apps.get_model('produto', 'ConfigEan')
    Ncm = apps.get_model('produto', 'Ncm')
    Grade = apps.get_model('produto', 'Grade')
    Tamanho = apps.get_model('produto', 'Tamanho')
    Cor = apps.get_model('produto', 'Cor')
    Material = apps.get_model('produto', 'Material')
    Unidade = apps.get_model('produto', 'Unidade')
    Codigos = apps.get_model('produto', 'Codigos')
    Produto = apps.get_model('produto', 'Produto')
    ProdutoDetalhe = apps.get_model('produto', 'ProdutoDetalhe')

    empresas = list(Empresa.objects.order_by('id'))
    empresa_padrao = empresas[0] if empresas else None
    if not empresa_padrao:
        return

    def clone_for_company(obj, empresa, unique_fields, copy_fields):
        if not obj:
            return None
        if getattr(obj, 'empresa_id', None) == empresa.id:
            return obj
        lookup = {'empresa': empresa}
        for field in unique_fields:
            lookup[field] = getattr(obj, field)
        defaults = {field: getattr(obj, field) for field in copy_fields}
        clone, _ = obj.__class__.objects.get_or_create(**lookup, defaults=defaults)
        return clone

    for model in (ConfigEan, Ncm, Grade, Tamanho, Cor, Material, Unidade, Codigos):
        model.objects.filter(empresa__isnull=True).update(empresa=empresa_padrao)

    for produto in Produto.objects.select_related(
        'empresa', 'unidade', 'material', 'grade'
    ).filter(empresa__isnull=False):
        empresa = produto.empresa

        unidade = clone_for_company(produto.unidade, empresa, ['Descricao'], ['Codigo'])
        material = clone_for_company(produto.material, empresa, ['Descricao'], ['Codigo', 'Status'])
        grade = clone_for_company(produto.grade, empresa, ['Descricao'], ['Status'])

        update_fields = []
        if unidade and unidade.pk != produto.unidade_id:
            produto.unidade = unidade
            update_fields.append('unidade')
        if material and material.pk != produto.material_id:
            produto.material = material
            update_fields.append('material')
        if grade and grade.pk != produto.grade_id:
            old_grade_id = produto.grade_id
            produto.grade = grade
            update_fields.append('grade')
        else:
            old_grade_id = produto.grade_id
        if update_fields:
            produto.save(update_fields=update_fields)

        if produto.ncm:
            original_ncm = Ncm.objects.filter(ncm=produto.ncm).order_by('id').first()
            if original_ncm:
                clone_for_company(original_ncm, empresa, ['ncm'], ['descricao', 'aliquota', 'campo1'])

        tamanho_map = {}
        if old_grade_id and grade:
            for tamanho in Tamanho.objects.filter(idgrade_id=old_grade_id).order_by('Idtamanho'):
                if tamanho.empresa_id == empresa.id and tamanho.idgrade_id == grade.pk:
                    tamanho_map[tamanho.pk] = tamanho
                    continue
                clone, _ = Tamanho.objects.get_or_create(
                    empresa=empresa,
                    idgrade=grade,
                    Tamanho=tamanho.Tamanho,
                    defaults={
                        'Descricao': tamanho.Descricao,
                        'Status': tamanho.Status,
                    },
                )
                tamanho_map[tamanho.pk] = clone

        for sku in ProdutoDetalhe.objects.select_related('idcor', 'idtamanho', 'config_ean').filter(produto=produto):
            changed = []
            cor = clone_for_company(sku.idcor, empresa, ['Codigo'], ['Descricao', 'Cor', 'Status'])
            if cor and cor.pk != sku.idcor_id:
                sku.idcor = cor
                changed.append('idcor')

            tamanho = tamanho_map.get(sku.idtamanho_id)
            if tamanho and tamanho.pk != sku.idtamanho_id:
                sku.idtamanho = tamanho
                changed.append('idtamanho')

            cfg = sku.config_ean
            if cfg and cfg.empresa_id != empresa.id:
                item_refs = list(
                    ProdutoDetalhe.objects.filter(
                        produto__empresa=empresa,
                        config_ean__country_prefix=cfg.country_prefix,
                        config_ean__company_prefix=cfg.company_prefix,
                    ).values_list('codigo_item_ref', flat=True)
                )
                next_ref = 1
                for item_ref in item_refs:
                    if str(item_ref).isdigit():
                        next_ref = max(next_ref, int(item_ref) + 1)
                cfg_clone, _ = ConfigEan.objects.get_or_create(
                    empresa=empresa,
                    country_prefix=cfg.country_prefix,
                    company_prefix=cfg.company_prefix,
                    defaults={
                        'next_itemref': max(cfg.next_itemref or 1, next_ref),
                        'ativo': cfg.ativo,
                    },
                )
                if cfg_clone.next_itemref < next_ref:
                    cfg_clone.next_itemref = next_ref
                    cfg_clone.save(update_fields=['next_itemref'])
                sku.config_ean = cfg_clone
                changed.append('config_ean')

            if changed:
                sku.save(update_fields=changed)

    for produto in Produto.objects.filter(empresa__isnull=False).exclude(referencia__isnull=True).exclude(referencia=''):
        partes = str(produto.referencia).split('-')
        if len(partes) != 3:
            continue
        aa, bb, resto = partes
        if len(resto) < 5 or not resto[-3:].isdigit():
            continue
        sequencial = int(resto[-3:]) + 1
        codigo, _ = Codigos.objects.get_or_create(
            empresa=produto.empresa,
            colecao=aa,
            estacao=bb,
            defaults={'valor_var': sequencial},
        )
        if codigo.valor_var < sequencial:
            codigo.valor_var = sequencial
            codigo.save(update_fields=['valor_var'])


def desfazer_separacao_auxiliares(apps, schema_editor):
    for model_name in ('ConfigEan', 'Ncm', 'Grade', 'Tamanho', 'Cor', 'Material', 'Unidade', 'Codigos'):
        Model = apps.get_model('produto', model_name)
        Model.objects.update(empresa=None)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_rename_cadastros_e_nome_c3e4c1_idx_cadastros_e_nome_1ec0bf_idx_and_more'),
        ('produto', '0009_empresa_produtos_base'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='codigos',
            name='unique_colecao_estacao',
        ),
        migrations.RemoveConstraint(
            model_name='colecao',
            name='uq_colecao_codigo_estacao',
        ),
        migrations.RemoveConstraint(
            model_name='configean',
            name='uq_country_company_prefix',
        ),
        migrations.RenameIndex(
            model_name='promocao',
            new_name='produto_pro_ativo_435620_idx',
            old_name='produto_pro_ativo_571397_idx',
        ),
        migrations.RenameIndex(
            model_name='promocao',
            new_name='produto_pro_escopo_91a70e_idx',
            old_name='produto_pro_escopo_d49f2a_idx',
        ),
        migrations.AddField(
            model_name='codigos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequenciais_produto', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='configean',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configs_ean', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='cor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cores_produto', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='grade',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades_produto', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='material',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais_produto', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='ncm',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncms', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='tamanho',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tamanhos_produto', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_produto', to='cadastros.empresa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='referencia',
            field=models.CharField(blank=True, help_text='Gerada automaticamente: AA-BB-CCDDD', max_length=11, null=True),
        ),
        migrations.RunPython(separar_auxiliares_por_empresa, desfazer_separacao_auxiliares),
        migrations.AddConstraint(
            model_name='codigos',
            constraint=models.UniqueConstraint(fields=('empresa', 'colecao', 'estacao'), name='unique_empresa_colecao_estacao'),
        ),
        migrations.AddConstraint(
            model_name='colecao',
            constraint=models.UniqueConstraint(fields=('empresa', 'Codigo', 'Estacao'), name='uq_empresa_colecao_codigo_estacao'),
        ),
        migrations.AddConstraint(
            model_name='configean',
            constraint=models.UniqueConstraint(fields=('empresa', 'country_prefix', 'company_prefix'), name='uq_empresa_country_company_prefix'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('empresa', 'referencia'), name='uq_empresa_produto_referencia'),
        ),
    ]
