# Generated by Django 4.2.11 on 2026-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_remove_codigos_unique_colecao_estacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtodetalhe',
            name='custo_original',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='produtodetalhe',
            name='custo_ultima_compra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
