# Generated by Django 4.2.11 on 2026-07-09 11:32

from decimal import Decimal

from django.db import migrations, models


def preencher_custo_medio(apps, schema_editor):
    ProdutoDetalhe = apps.get_model('produto', 'ProdutoDetalhe')
    for sku in ProdutoDetalhe.objects.all().iterator():
        custo = Decimal(sku.custo_ultima_compra or sku.custo_original or 0)
        if custo > 0:
            sku.custo_medio = custo
            sku.save(update_fields=['custo_medio'])


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_backfill_custo_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquemovimentacao',
            name='custo_medio_apos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='estoquemovimentacao',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='estoquemovimentacao',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='produtodetalhe',
            name='custo_medio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.RunPython(preencher_custo_medio, migrations.RunPython.noop),
    ]
