# Generated by Django 4.2.11 on 2026-07-13 14:47

from django.db import migrations, models


def popular_ncms_moda(apps, schema_editor):
    Empresa = apps.get_model('cadastros', 'Empresa')
    Ncm = apps.get_model('produto', 'Ncm')
    ncms = [
        ("6204.62.00", "Calças, jardineiras e shorts femininos de algodão", "VESTUARIO", "18.00"),
        ("6204.42.00", "Vestidos femininos de algodão", "VESTUARIO", "18.00"),
        ("6206.30.00", "Blusas, camisas e camisetes femininas de algodão", "VESTUARIO", "18.00"),
        ("6204.59.00", "Saias e saias-calças femininas de outras matérias têxteis", "VESTUARIO", "18.00"),
        ("5208.52.00", "Tecidos de algodão estampados", "TECIDO", "18.00"),
        ("6006.22.00", "Tecidos de malha de algodão tingidos", "TECIDO", "18.00"),
        ("5806.32.00", "Fitas de fibras sintéticas ou artificiais", "AVIAMENTO", "18.00"),
        ("9606.21.00", "Botões de plástico, não recobertos de matérias têxteis", "AVIAMENTO", "18.00"),
        ("9607.19.00", "Fechos e zíperes com dentes de outras matérias", "AVIAMENTO", "18.00"),
        ("4819.40.00", "Sacos, sacolas e embalagens de papel", "EMBALAGEM", "18.00"),
    ]
    for empresa in Empresa.objects.all():
        for ncm, descricao, categoria, aliquota in ncms:
            Ncm.objects.update_or_create(
                empresa=empresa,
                ncm=ncm,
                defaults={
                    "descricao": descricao,
                    "categoria": categoria,
                    "aliquota": aliquota,
                    "ativo": True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0024_ordemproducaoitem_faccao'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fichatecnica',
            new_name='produto_fic_empresa_89ff80_idx',
            old_name='produto_fic_empresa_08bd3c_idx',
        ),
        migrations.RenameIndex(
            model_name='fichatecnica',
            new_name='produto_fic_status_4c299f_idx',
            old_name='produto_fic_status_94d4df_idx',
        ),
        migrations.RenameIndex(
            model_name='fichatecnica',
            new_name='produto_fic_ativa_14f2f4_idx',
            old_name='produto_fic_ativa_38b5bb_idx',
        ),
        migrations.RenameIndex(
            model_name='fichatecnicaitem',
            new_name='produto_fic_ficha_i_ef0081_idx',
            old_name='produto_fic_ficha_i_0f08cd_idx',
        ),
        migrations.RenameIndex(
            model_name='fichatecnicaitem',
            new_name='produto_fic_produto_1e2b0e_idx',
            old_name='produto_fic_produto_d2fe09_idx',
        ),
        migrations.RenameIndex(
            model_name='fichatecnicaitem',
            new_name='produto_fic_fornece_021299_idx',
            old_name='produto_fic_fornece_93a9d6_idx',
        ),
        migrations.RenameIndex(
            model_name='ordemproducao',
            new_name='produto_ord_empresa_bbee41_idx',
            old_name='produto_ord_empresa_55be13_idx',
        ),
        migrations.RenameIndex(
            model_name='ordemproducao',
            new_name='produto_ord_produto_b39fa0_idx',
            old_name='produto_ord_produto_3d6e20_idx',
        ),
        migrations.RenameIndex(
            model_name='ordemproducao',
            new_name='produto_ord_ficha_t_34cec8_idx',
            old_name='produto_ord_ficha__4df699_idx',
        ),
        migrations.RenameIndex(
            model_name='ordemproducao',
            new_name='produto_ord_sku_fin_0b61b6_idx',
            old_name='produto_ord_sku_fin_b68bea_idx',
        ),
        migrations.RenameIndex(
            model_name='ordemproducaograde',
            new_name='produto_ord_ordem_i_41918a_idx',
            old_name='produto_ord_ordem_i_4ca92c_idx',
        ),
        migrations.RenameIndex(
            model_name='ordemproducaograde',
            new_name='produto_ord_sku_fin_df665c_idx',
            old_name='produto_ord_sku_fin_4ef8d7_idx',
        ),
        migrations.RenameIndex(
            model_name='ordemproducaoitem',
            new_name='produto_ord_ordem_i_28c237_idx',
            old_name='produto_ord_ordem_i_10e52c_idx',
        ),
        migrations.RenameIndex(
            model_name='ordemproducaoitem',
            new_name='produto_ord_produto_293bfc_idx',
            old_name='produto_ord_produto_04d9ef_idx',
        ),
        migrations.RenameIndex(
            model_name='ordemproducaoitem',
            new_name='produto_ord_status__ad3270_idx',
            old_name='produto_ord_status__5a4c1d_idx',
        ),
        migrations.AddField(
            model_name='ncm',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='ncm',
            name='categoria',
            field=models.CharField(choices=[('VESTUARIO', 'Vestuário'), ('TECIDO', 'Tecidos'), ('AVIAMENTO', 'Aviamentos'), ('EMBALAGEM', 'Embalagens'), ('OUTROS', 'Outros')], db_index=True, default='OUTROS', max_length=20),
        ),
        migrations.RunPython(popular_ncms_moda, migrations.RunPython.noop),
    ]
