# Generated by Django 4.2.11 on 2026-08-12 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0027_inventario_validacao_contado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoVendaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Criação'), ('ALTERACAO_CADASTRAL', 'Alteração cadastral'), ('ALTERACAO_FISCAL', 'Alteração fiscal'), ('SKU_CRIADO', 'SKU criado'), ('SKU_INATIVADO', 'SKU inativado'), ('SKU_REATIVADO', 'SKU reativado'), ('ATIVACAO', 'Ativação'), ('INATIVACAO', 'Inativação'), ('BLOQUEIO_VENDA', 'Bloqueio de venda'), ('DESBLOQUEIO_VENDA', 'Desbloqueio de venda'), ('IMAGEM_INCLUIDA', 'Imagem incluída'), ('IMAGEM_REMOVIDA', 'Imagem removida'), ('IMAGEM_PRINCIPAL', 'Imagem principal')], db_index=True, max_length=30)),
                ('descricao', models.TextField(blank=True, default='')),
                ('dados_anteriores', models.JSONField(blank=True, default=dict)),
                ('dados_novos', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_produto_venda', to='cadastros.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_venda', to='produto.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_produto_venda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_evento', '-id'],
                'indexes': [models.Index(fields=['empresa', 'produto', '-data_evento'], name='produto_pro_empresa_6c69bb_idx'), models.Index(fields=['produto', 'tipo_evento'], name='produto_pro_produto_2cbffc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='produtos/imagens/')),
                ('imagem_reduzida', models.FileField(blank=True, null=True, upload_to='produtos/imagens/reduzidas/')),
                ('principal', models.BooleanField(db_index=True, default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produto.produto')),
            ],
            options={
                'ordering': ['ordem', 'id'],
                'indexes': [models.Index(fields=['produto', 'principal'], name='produto_pro_produto_1e7301_idx'), models.Index(fields=['produto', 'ordem'], name='produto_pro_produto_1c31c3_idx')],
            },
        ),
    ]
