# Generated by Django 4.2.11 on 2026-08-13 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


def backfill_referencias_uso_consumo(apps, schema_editor):
    Produto = apps.get_model('produto', 'Produto')
    Sequencia = apps.get_model('produto', 'ProdutoUsoConsumoSequencia')
    for empresa_id in Produto.objects.filter(tipo_produto='2', empresa__isnull=False).values_list('empresa_id', flat=True).distinct():
        usados = set(
            Produto.objects
            .filter(empresa_id=empresa_id, referencia__startswith='USO-')
            .values_list('referencia', flat=True)
        )
        proximo = 1
        for produto in Produto.objects.filter(empresa_id=empresa_id, tipo_produto='2').order_by('Idproduto'):
            if produto.referencia:
                match = re.fullmatch(r'USO-(\d{6})', str(produto.referencia))
                if match:
                    proximo = max(proximo, int(match.group(1)) + 1)
                continue
            while True:
                referencia = f'USO-{proximo:06d}'
                proximo += 1
                if referencia not in usados:
                    usados.add(referencia)
                    Produto.objects.filter(pk=produto.pk).update(referencia=referencia)
                    break
        Sequencia.objects.update_or_create(empresa_id=empresa_id, defaults={'proximo_numero': proximo})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        ('produto', '0028_produtovendahistorico_produtoimagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoUsoConsumoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'produto_uso_consumo_estoque',
            },
        ),
        migrations.CreateModel(
            name='ProdutoUsoConsumoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Criação'), ('ALTERACAO_CADASTRAL', 'Alteração cadastral'), ('ALTERACAO_FISCAL', 'Alteração fiscal'), ('ATIVACAO', 'Ativação'), ('INATIVACAO', 'Inativação'), ('EXCLUSAO', 'Exclusão'), ('ENTRADA_ESTOQUE', 'Entrada de estoque'), ('CONSUMO_INTERNO', 'Consumo interno'), ('AJUSTE_ESTOQUE', 'Ajuste de estoque')], db_index=True, max_length=30)),
                ('descricao', models.TextField(blank=True, default='')),
                ('dados_anteriores', models.JSONField(blank=True, default=dict)),
                ('dados_novos', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-data_evento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoUsoConsumoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('CONSUMO_INTERNO', 'Consumo interno'), ('AJUSTE_ENTRADA', 'Ajuste de entrada'), ('AJUSTE_SAIDA', 'Ajuste de saída')], db_index=True, max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('saldo_anterior', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('saldo_posterior', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('data_movimento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('destino', models.CharField(blank=True, default='', max_length=255)),
                ('documento', models.CharField(blank=True, default='', max_length=80)),
                ('origem', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'db_table': 'produto_uso_consumo_movimentacao',
                'ordering': ['-data_movimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoUsoConsumoSequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proximo_numero', models.PositiveIntegerField(default=1)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'produto_uso_consumo_sequencia',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='controla_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['controla_estoque'], name='produto_pro_control_c48a3e_idx'),
        ),
        migrations.AddField(
            model_name='produtousoconsumosequencia',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sequencia_produto_uso_consumo', to='cadastros.empresa'),
        ),
        migrations.RunPython(backfill_referencias_uso_consumo, noop_reverse),
        migrations.AddField(
            model_name='produtousoconsumomovimentacao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_produto_uso_consumo', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='produtousoconsumomovimentacao',
            name='loja_matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_produto_uso_consumo', to='cadastros.loja'),
        ),
        migrations.AddField(
            model_name='produtousoconsumomovimentacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_uso_consumo', to='produto.produto'),
        ),
        migrations.AddField(
            model_name='produtousoconsumomovimentacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_produto_uso_consumo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produtousoconsumohistorico',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_produto_uso_consumo', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='produtousoconsumohistorico',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_uso_consumo', to='produto.produto'),
        ),
        migrations.AddField(
            model_name='produtousoconsumohistorico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_produto_uso_consumo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produtousoconsumoestoque',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques_produto_uso_consumo', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='produtousoconsumoestoque',
            name='loja_matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques_produto_uso_consumo', to='cadastros.loja'),
        ),
        migrations.AddField(
            model_name='produtousoconsumoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_uso_consumo', to='produto.produto'),
        ),
        migrations.AddIndex(
            model_name='produtousoconsumomovimentacao',
            index=models.Index(fields=['empresa', 'produto', '-data_movimento'], name='produto_uso_empresa_78f804_idx'),
        ),
        migrations.AddIndex(
            model_name='produtousoconsumomovimentacao',
            index=models.Index(fields=['tipo', 'data_movimento'], name='produto_uso_tipo_02bf55_idx'),
        ),
        migrations.AddIndex(
            model_name='produtousoconsumohistorico',
            index=models.Index(fields=['empresa', 'produto', '-data_evento'], name='produto_pro_empresa_565224_idx'),
        ),
        migrations.AddIndex(
            model_name='produtousoconsumohistorico',
            index=models.Index(fields=['produto', 'tipo_evento'], name='produto_pro_produto_66f73d_idx'),
        ),
        migrations.AddIndex(
            model_name='produtousoconsumoestoque',
            index=models.Index(fields=['empresa', 'produto'], name='produto_uso_empresa_226f50_idx'),
        ),
        migrations.AddIndex(
            model_name='produtousoconsumoestoque',
            index=models.Index(fields=['loja_matriz'], name='produto_uso_loja_ma_dadcab_idx'),
        ),
        migrations.AddConstraint(
            model_name='produtousoconsumoestoque',
            constraint=models.UniqueConstraint(fields=('empresa', 'produto', 'loja_matriz'), name='uq_uso_consumo_estoque_empresa_produto_matriz'),
        ),
    ]
