# Generated by Django 4.2.11 on 2026-08-14 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0030_corrige_produto_uso_consumo_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoInsumoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Criação'), ('ALTERACAO_CADASTRAL', 'Alteração cadastral'), ('ALTERACAO_FISCAL', 'Alteração fiscal'), ('ATIVACAO', 'Ativação'), ('INATIVACAO', 'Inativação'), ('EXCLUSAO', 'Exclusão')], db_index=True, max_length=30)),
                ('descricao', models.TextField(blank=True, default='')),
                ('dados_anteriores', models.JSONField(blank=True, default=dict)),
                ('dados_novos', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_produto_insumo', to='cadastros.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_insumo', to='produto.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_produto_insumo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_evento', '-id'],
                'indexes': [models.Index(fields=['empresa', 'produto', '-data_evento'], name='produto_pro_empresa_3dbd25_idx'), models.Index(fields=['produto', 'tipo_evento'], name='produto_pro_produto_76e94e_idx')],
            },
        ),
    ]
