# Generated by Django 4.2.11 on 2026-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0031_produtoinsumohistorico'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('empresa', 'Descricao'), name='uq_empresa_grade_descricao_aux'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('empresa', 'Codigo'), name='uq_empresa_grupo_codigo_aux'),
        ),
        migrations.AddConstraint(
            model_name='subgrupo',
            constraint=models.UniqueConstraint(fields=('empresa', 'Idgrupo', 'Descricao'), name='uq_empresa_grupo_subgrupo_desc_aux'),
        ),
        migrations.AddConstraint(
            model_name='tamanho',
            constraint=models.UniqueConstraint(fields=('empresa', 'idgrade', 'Tamanho'), name='uq_empresa_grade_tamanho_aux'),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(fields=('empresa', 'Codigo'), name='uq_empresa_unidade_codigo_aux'),
        ),
    ]
