# Generated by Django 4.2.11 on 2026-08-26 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        ('produto', '0032_grade_uq_empresa_grade_descricao_aux_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto_fornecedor', models.CharField(max_length=80)),
                ('codigo_normalizado', models.CharField(db_index=True, max_length=80)),
                ('codigo_vigente', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('descricao_fornecedor', models.CharField(blank=True, default='', max_length=255)),
                ('gtin_ean', models.CharField(blank=True, default='', max_length=14, validators=[django.core.validators.RegexValidator('^\\d{8,14}$', 'GTIN/EAN deve conter entre 8 e 14 dígitos.')])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_fornecedor_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_fornecedor', to='cadastros.empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_sysvar', to='cadastros.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_fornecedor', to='produto.produto')),
            ],
            options={
                'db_table': 'produto_fornecedor',
                'indexes': [models.Index(fields=['empresa', 'fornecedor', 'codigo_normalizado'], name='ix_prod_forn_emp_forn_cod'), models.Index(fields=['empresa', 'produto'], name='ix_prod_forn_emp_prod'), models.Index(fields=['gtin_ean'], name='ix_prod_forn_gtin_ean')],
            },
        ),
        migrations.AddConstraint(
            model_name='produtofornecedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'fornecedor', 'codigo_vigente'), name='uq_prod_forn_codigo_vigente'),
        ),
    ]
