# Generated by Django 4.2.11 on 2026-08-26 13:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0033_produto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtofornecedor',
            name='fator_conversao',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AddField(
            model_name='produtofornecedor',
            name='unidade_fornecedor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
