# Generated by Django 4.2.11 on 2025-11-07 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_nat_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('Idformapagamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=120)),
                ('num_parcelas', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'financeiro_forma_pagamento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Pagar',
            fields=[
                ('Idpagar', models.BigAutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=60)),
                ('Documento', models.CharField(blank=True, max_length=30, null=True)),
                ('Data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('Valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Previsao', models.BooleanField(default=False)),
                ('FormaPagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('conta_contabil', models.CharField(blank=True, max_length=50, null=True)),
                ('pedido_compra', models.IntegerField(blank=True, null=True)),
                ('nfe_id', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Idnatureza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.nat_lancamento')),
                ('idfornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor')),
                ('idloja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.loja')),
            ],
            options={
                'db_table': 'financeiro_pagar',
            },
        ),
        migrations.CreateModel(
            name='PagarItem',
            fields=[
                ('Idpagaritem', models.BigAutoField(primary_key=True, serialize=False)),
                ('parcela_n', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('EFETIVO', 'Efetivo'), ('BAIXADO', 'Baixado'), ('CANCELADO', 'Cancelado')], default='PREVISTO', max_length=10)),
                ('Data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=18)),
                ('FormaPagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('idconta', models.IntegerField(blank=True, null=True)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('data_baixa', models.DateField(blank=True, null=True)),
                ('valor_baixa', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Previsao', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Idnatureza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.nat_lancamento')),
                ('Idpagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.pagar')),
            ],
            options={
                'db_table': 'financeiro_pagar_item',
            },
        ),
        migrations.CreateModel(
            name='PagarRateio',
            fields=[
                ('Idrateio', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('centro_custo', models.CharField(blank=True, max_length=50, null=True)),
                ('Idnatureza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.nat_lancamento')),
                ('Idpagaritem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='financeiro.pagaritem')),
            ],
            options={
                'db_table': 'financeiro_pagar_rateio',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamentoParcela',
            fields=[
                ('Idformapagparcela', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordem', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.formapagamento')),
            ],
            options={
                'db_table': 'financeiro_forma_pagamento_parcela',
                'ordering': ['forma', 'ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='pagaritem',
            index=models.Index(fields=['status'], name='financeiro__status_bab50f_idx'),
        ),
        migrations.AddIndex(
            model_name='pagaritem',
            index=models.Index(fields=['Data_vencimento'], name='financeiro__Data_ve_566485_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagaritem',
            constraint=models.UniqueConstraint(fields=('Idpagar', 'parcela_n'), name='uq_pagar_parcela'),
        ),
        migrations.AddIndex(
            model_name='pagar',
            index=models.Index(fields=['idloja', 'idfornecedor', 'Data_emissao'], name='financeiro__idloja__fe9164_idx'),
        ),
        migrations.AddIndex(
            model_name='formapagamentoparcela',
            index=models.Index(fields=['forma', 'ordem'], name='financeiro__forma_i_45ff64_idx'),
        ),
        migrations.AddConstraint(
            model_name='formapagamentoparcela',
            constraint=models.UniqueConstraint(fields=('forma', 'ordem'), name='uq_formapag_parcela_ordem'),
        ),
    ]
