# Generated by Django 4.2.11 on 2026-05-29 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_loja_contacontabil_loja_dataabertura_and_more'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receber',
            fields=[
                ('Idreceber', models.BigAutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=60)),
                ('Documento', models.CharField(blank=True, max_length=30, null=True)),
                ('Data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('Valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Previsao', models.BooleanField(default=False)),
                ('FormaPagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('conta_contabil', models.CharField(blank=True, max_length=50, null=True)),
                ('pedido_venda', models.IntegerField(blank=True, null=True)),
                ('nfe_id', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Idnatureza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.nat_lancamento')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente')),
                ('idloja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.loja')),
            ],
            options={
                'db_table': 'financeiro_receber',
            },
        ),
        migrations.CreateModel(
            name='ReceberItem',
            fields=[
                ('Idreceberitem', models.BigAutoField(primary_key=True, serialize=False)),
                ('parcela_n', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('EFETIVO', 'Efetivo'), ('BAIXADO', 'Baixado'), ('CANCELADO', 'Cancelado')], default='PREVISTO', max_length=10)),
                ('Data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=18)),
                ('FormaPagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('idconta', models.IntegerField(blank=True, null=True)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('data_baixa', models.DateField(blank=True, null=True)),
                ('valor_baixa', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Previsao', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Idnatureza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.nat_lancamento')),
                ('Idreceber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.receber')),
            ],
            options={
                'db_table': 'financeiro_receber_item',
            },
        ),
        migrations.CreateModel(
            name='ReceberRateio',
            fields=[
                ('Idrateio', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('centro_custo', models.CharField(blank=True, max_length=50, null=True)),
                ('Idnatureza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.nat_lancamento')),
                ('Idreceberitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='financeiro.receberitem')),
            ],
            options={
                'db_table': 'financeiro_receber_rateio',
            },
        ),
        migrations.AddIndex(
            model_name='receberitem',
            index=models.Index(fields=['status'], name='financeiro__status_7f0bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='receberitem',
            index=models.Index(fields=['Data_vencimento'], name='financeiro__Data_ve_9bcc28_idx'),
        ),
        migrations.AddConstraint(
            model_name='receberitem',
            constraint=models.UniqueConstraint(fields=('Idreceber', 'parcela_n'), name='uq_receber_parcela'),
        ),
        migrations.AddIndex(
            model_name='receber',
            index=models.Index(fields=['idloja', 'idcliente', 'Data_emissao'], name='financeiro__idloja__bd4437_idx'),
        ),
    ]
