# Generated by Django 4.2.11 on 2026-05-29 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_loja_contacontabil_loja_dataabertura_and_more'),
        ('financeiro', '0002_receber_receberitem_receberrateio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('Idcaixa', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=120)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ativo', models.BooleanField(default=True)),
                ('data_abertura', models.DateField(default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('idloja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to='cadastros.loja')),
            ],
            options={
                'db_table': 'financeiro_caixa',
                'ordering': ['idloja', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('Idconta', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120)),
                ('banco', models.CharField(max_length=80)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=30)),
                ('tipo_conta', models.CharField(choices=[('CORRENTE', 'Conta corrente'), ('POUPANCA', 'Poupança'), ('PAGAMENTO', 'Conta pagamento')], default='CORRENTE', max_length=15)),
                ('pix_chave', models.CharField(blank=True, max_length=120, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('idloja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_bancarias', to='cadastros.loja')),
            ],
            options={
                'db_table': 'financeiro_conta_bancaria',
                'ordering': ['idloja', 'banco', 'agencia', 'conta'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('Idmovimentacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_movimento', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência')], max_length=15)),
                ('status', models.CharField(choices=[('PREVISTA', 'Prevista'), ('EFETIVA', 'Efetiva'), ('CANCELADA', 'Cancelada')], db_index=True, default='EFETIVA', max_length=10)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('PAGAR', 'Contas a pagar'), ('RECEBER', 'Contas a receber')], db_index=True, default='MANUAL', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('historico', models.CharField(max_length=255)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('FormaPagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Idnatureza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.nat_lancamento')),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.caixa')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.contabancaria')),
                ('idloja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.loja')),
                ('pagar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='financeiro.pagaritem')),
                ('receber_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='financeiro.receberitem')),
            ],
            options={
                'db_table': 'financeiro_movimentacao',
                'ordering': ['-data_movimento', '-Idmovimentacao'],
                'indexes': [models.Index(fields=['idloja', 'data_movimento'], name='financeiro__idloja__5c73e9_idx'), models.Index(fields=['tipo', 'status'], name='financeiro__tipo_1f5cd1_idx'), models.Index(fields=['caixa'], name='financeiro__caixa_i_792785_idx'), models.Index(fields=['conta_bancaria'], name='financeiro__conta_b_284620_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contabancaria',
            index=models.Index(fields=['idloja', 'ativo'], name='financeiro__idloja__eef535_idx'),
        ),
        migrations.AddIndex(
            model_name='contabancaria',
            index=models.Index(fields=['banco', 'agencia', 'conta'], name='financeiro__banco_65995a_idx'),
        ),
        migrations.AddConstraint(
            model_name='contabancaria',
            constraint=models.UniqueConstraint(fields=('idloja', 'banco', 'agencia', 'conta'), name='uq_conta_bancaria'),
        ),
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['idloja', 'ativo'], name='financeiro__idloja__8a68fa_idx'),
        ),
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['codigo'], name='financeiro__codigo_8e3ec9_idx'),
        ),
        migrations.AddConstraint(
            model_name='caixa',
            constraint=models.UniqueConstraint(fields=('idloja', 'codigo'), name='uq_caixa_loja_codigo'),
        ),
    ]
