# Generated by Django 4.2.11 on 2026-05-31 00:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Sum
from django.utils import timezone


def criar_caixa_master(apps, schema_editor):
    Caixa = apps.get_model('financeiro', 'Caixa')
    total_lojas = Caixa.objects.filter(tipo_caixa='LOJA').aggregate(total=Sum('saldo_atual')).get('total') or Decimal('0.00')
    Caixa.objects.get_or_create(
        tipo_caixa='MASTER',
        codigo='MASTER',
        defaults={
            'idloja_id': None,
            'descricao': 'Caixa Master do Grupo',
            'saldo_inicial': Decimal('0.00'),
            'saldo_atual': total_lojas,
            'ativo': True,
            'data_abertura': timezone.localdate(),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_funcionarios_comissao_percentual'),
        ('financeiro', '0003_caixa_contabancaria_movimentacaofinanceira_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'ordering': ['tipo_caixa', 'idloja', 'codigo']},
        ),
        migrations.AddField(
            model_name='caixa',
            name='tipo_caixa',
            field=models.CharField(choices=[('LOJA', 'Caixa da loja'), ('MASTER', 'Caixa master do grupo')], db_index=True, default='LOJA', max_length=10),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='idloja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to='cadastros.loja'),
        ),
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['tipo_caixa', 'ativo'], name='financeiro__tipo_ca_e0ccd4_idx'),
        ),
        migrations.RunPython(criar_caixa_master, migrations.RunPython.noop),
    ]
