# Generated by Django 4.2.11 on 2026-07-05 13:29

from django.db import migrations, models


def vincular_formas_empresa(apps, schema_editor):
    Empresa = apps.get_model('cadastros', 'Empresa')
    FormaPagamento = apps.get_model('financeiro', 'FormaPagamento')
    FormaPagamentoParcela = apps.get_model('financeiro', 'FormaPagamentoParcela')

    empresas = list(Empresa.objects.order_by('id'))
    if not empresas:
        return
    empresa_padrao = empresas[0]
    FormaPagamento.objects.filter(empresa__isnull=True).update(empresa=empresa_padrao)

    base = list(FormaPagamento.objects.filter(empresa=empresa_padrao).prefetch_related('parcelas').order_by('Idformapagamento'))
    for empresa in empresas[1:]:
        for forma in base:
            clone, _ = FormaPagamento.objects.get_or_create(
                empresa=empresa,
                codigo=forma.codigo,
                defaults={
                    'descricao': forma.descricao,
                    'num_parcelas': forma.num_parcelas,
                    'ativo': forma.ativo,
                },
            )
            if not FormaPagamentoParcela.objects.filter(forma=clone).exists():
                for parcela in forma.parcelas.all():
                    FormaPagamentoParcela.objects.create(
                        forma=clone,
                        ordem=parcela.ordem,
                        dias=parcela.dias,
                        percentual=parcela.percentual,
                        valor_fixo=parcela.valor_fixo,
                    )


def desvincular_formas_empresa(apps, schema_editor):
    FormaPagamento = apps.get_model('financeiro', 'FormaPagamento')
    FormaPagamento.objects.update(empresa=None)


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_empresa_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.RunPython(vincular_formas_empresa, desvincular_formas_empresa),
        migrations.AddConstraint(
            model_name='formapagamento',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_empresa_forma_pagamento_codigo'),
        ),
    ]
