# Generated by Django 4.2.11 on 2026-07-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_alter_formapagamento_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='origem',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PAGAR', 'Contas a pagar'), ('RECEBER', 'Contas a receber'), ('TRANSFERENCIA', 'Transferência entre caixas')], db_index=True, default='MANUAL', max_length=15),
        ),
    ]
