# Generated by Django 4.2.11 on 2026-07-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_alter_movimentacaofinanceira_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='adquirente',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='conta_liquidacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formas_liquidacao', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='gera_recebivel_bancario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='prazo_credito_dias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='taxa_fixa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='taxa_percentual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='origem',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PAGAR', 'Contas a pagar'), ('RECEBER', 'Contas a receber'), ('TRANSFERENCIA', 'Transferência entre caixas'), ('CARTAO', 'Recebível de cartão')], db_index=True, default='MANUAL', max_length=15),
        ),
    ]
