# Generated by Django 4.2.11 on 2026-07-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_formapagamento_adquirente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='data_conciliacao',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='valor_conciliado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
