# Generated by Django 4.2.11 on 2026-07-07 19:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_planocontabil_classe'),
        ('financeiro', '0012_antecipacao_recebivel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('Idlancamentocontabil', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_lancamento', models.DateField(db_index=True)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('historico', models.CharField(max_length=255)),
                ('origem', models.CharField(db_index=True, max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('PENDENTE', 'Pendente'), ('ESTORNADO', 'Estornado')], db_index=True, default='GERADO', max_length=10)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'financeiro_lancamento_contabil',
                'ordering': ['-data_lancamento', '-Idlancamentocontabil'],
            },
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='conta_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_credito', to='cadastros.planocontabil'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='conta_debito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_debito', to='cadastros.planocontabil'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_contabeis', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='idloja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.loja'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='movimentacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lancamento_contabil', to='financeiro.movimentacaofinanceira'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='natureza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_contabeis', to='cadastros.nat_lancamento'),
        ),
        migrations.AddIndex(
            model_name='lancamentocontabil',
            index=models.Index(fields=['empresa', 'data_lancamento'], name='financeiro__empresa_17b406_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocontabil',
            index=models.Index(fields=['status'], name='financeiro__status_02bd98_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocontabil',
            index=models.Index(fields=['origem'], name='financeiro__origem_81ce2d_idx'),
        ),
    ]
