# Generated by Django 4.2.11 on 2026-07-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_planocontabil_classe'),
        ('financeiro', '0015_alter_movimentacaofinanceira_origem_comissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'financeiro_config_financeira',
            },
        ),
        migrations.AddField(
            model_name='pagaritem',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pagaritem',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='configfinanceira',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='config_financeira', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='configfinanceira',
            name='natureza_descontos_concedidos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.nat_lancamento'),
        ),
        migrations.AddField(
            model_name='configfinanceira',
            name='natureza_descontos_obtidos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.nat_lancamento'),
        ),
        migrations.AddField(
            model_name='configfinanceira',
            name='natureza_juros_pagos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.nat_lancamento'),
        ),
        migrations.AddField(
            model_name='configfinanceira',
            name='natureza_juros_recebidos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.nat_lancamento'),
        ),
        migrations.AddField(
            model_name='configfinanceira',
            name='natureza_multas_pagas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.nat_lancamento'),
        ),
        migrations.AddField(
            model_name='configfinanceira',
            name='natureza_multas_recebidas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.nat_lancamento'),
        ),
        migrations.AddField(
            model_name='configfinanceira',
            name='natureza_tarifas_pagas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.nat_lancamento'),
        ),
    ]
