# Generated by Django 4.2.11 on 2026-07-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_formapagamento_tef'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='antecipacaorecebivel',
            new_name='financeiro__empresa_c8fd7f_idx',
            old_name='financeiro__empresa_1e920c_idx',
        ),
        migrations.RenameIndex(
            model_name='antecipacaorecebivel',
            new_name='financeiro__conta_b_999c58_idx',
            old_name='financeiro__conta_b_5a06c7_idx',
        ),
        migrations.RenameIndex(
            model_name='antecipacaorecebivelitem',
            new_name='financeiro__antecip_0adca7_idx',
            old_name='financeiro__antecipa_0906d5_idx',
        ),
        migrations.RenameIndex(
            model_name='antecipacaorecebivelitem',
            new_name='financeiro__receber_53614d_idx',
            old_name='financeiro__receber_9efdb0_idx',
        ),
    ]
