# Generated by Django 4.2.11 on 2026-08-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_rename_prazo_pagamento_parcela_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagar',
            name='alerta_divergencia_mercadoria',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pagar',
            name='valor_divergencia_mercadoria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
