# Generated by Django 4.2.11 on 2026-09-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0040_nfce_hub_fields'),
        ('financeiro', '0030_adquirentes_condicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receberitem',
            name='adquirente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebiveis', to='financeiro.adquirente'),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='condicao_adquirente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebiveis', to='financeiro.condicaoadquirente'),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='forma_pagamento_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebiveis', to='financeiro.formapagamento'),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='parcela_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='prazo_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebiveis', to='financeiro.prazopagamento'),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='taxa_fixa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='taxa_percentual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='valor_liquido_previsto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='valor_taxa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='receberitem',
            name='venda_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebiveis', to='fiscal.vendapdvpagamento'),
        ),
    ]
