# Generated by Django 4.2.11 on 2026-09-11 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0029_centrocusto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysvarHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('nome', models.CharField(default='Sysvar Hub', max_length=120)),
                ('token_hash', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('token_prefixo', models.CharField(blank=True, default='', max_length=12)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('ultimo_contato', models.DateTimeField(blank=True, null=True)),
                ('versao', models.CharField(blank=True, default='', max_length=40)),
                ('hostname', models.CharField(blank=True, default='', max_length=120)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sysvar_hub', to='cadastros.loja')),
            ],
            options={
                'ordering': ['loja_id'],
            },
        ),
    ]
