# Generated by Django 4.2.11 on 2026-09-11 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0029_centrocusto'),
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtivacaoSysvarHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('codigo_prefixo', models.CharField(db_index=True, max_length=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(db_index=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativacoes_sysvar_hub', to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativacoes', to='hub.sysvarhub')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativacoes_sysvar_hub', to='cadastros.loja')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['loja', 'codigo_prefixo'], name='ix_ativ_hub_loja_pref'), models.Index(fields=['expira_em', 'usado_em'], name='ix_ativ_hub_exp_uso')],
            },
        ),
    ]
