# Generated by Django 4.2.11 on 2026-09-17 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0026_nfe_xml_efetivacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscal', '0039_notafiscalentrada_xml_fornecedor'),
        ('cadastros', '0029_centrocusto'),
        ('hub', '0002_ativacaosysvarhub'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubVendaMapeamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda_uuid', models.UUIDField()),
                ('documento', models.CharField(db_index=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_mapeadas', to='hub.sysvarhub')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeamentos_hub', to='fiscal.vendapdv')),
            ],
        ),
        migrations.CreateModel(
            name='HubSessaoCaixaRecebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_uuid', models.UUIDField()),
                ('terminal', models.CharField(blank=True, default='', max_length=80)),
                ('aberto_em', models.DateTimeField(blank=True, null=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_contado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('situacao', models.CharField(blank=True, default='', max_length=40)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_hub', to='financeiro.caixa')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa_recebidas', to='hub.sysvarhub')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_caixa_hub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HubMovimentoCaixaRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimento_uuid', models.UUIDField()),
                ('tipo', models.CharField(db_index=True, max_length=20)),
                ('terminal', models.CharField(blank=True, default='', max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('historico', models.CharField(blank=True, default='', max_length=255)),
                ('documento', models.CharField(blank=True, default='', max_length=80)),
                ('tipo_despesa', models.CharField(blank=True, default='', max_length=80)),
                ('ocorrido_em', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_hub', to='financeiro.caixa')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa_recebidos', to='hub.sysvarhub')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa_hub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HubFechamentoDiaRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechamento_uuid', models.UUIDField()),
                ('data_operacional', models.DateField()),
                ('total_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_conferido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('situacao', models.CharField(blank=True, default='', max_length=40)),
                ('formas_pagamento', models.JSONField(blank=True, default=list)),
                ('terminal', models.CharField(blank=True, default='', max_length=80)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_dia_recebidos', to='hub.sysvarhub')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_dia_hub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HubEventoRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_uuid', models.UUIDField()),
                ('chave_idempotencia', models.CharField(max_length=120)),
                ('tipo', models.CharField(db_index=True, max_length=40)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSADO', 'Processado'), ('DUPLICADO', 'Duplicado'), ('ERRO', 'Erro'), ('CONFLITO', 'Conflito')], db_index=True, default='RECEBIDO', max_length=12)),
                ('mensagem_erro', models.CharField(blank=True, default='', max_length=255)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_recebidos', to='hub.sysvarhub')),
            ],
            options={
                'ordering': ['-recebido_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HubClienteMapeamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_uuid', models.UUIDField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeamentos_hub', to='cadastros.cliente')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_mapeados', to='hub.sysvarhub')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hubvendamapeamento',
            constraint=models.UniqueConstraint(fields=('hub', 'venda_uuid'), name='uq_hub_venda_uuid'),
        ),
        migrations.AddConstraint(
            model_name='hubsessaocaixarecebida',
            constraint=models.UniqueConstraint(fields=('hub', 'sessao_uuid'), name='uq_hub_sessao_uuid'),
        ),
        migrations.AddConstraint(
            model_name='hubmovimentocaixarecebido',
            constraint=models.UniqueConstraint(fields=('hub', 'movimento_uuid'), name='uq_hub_mov_caixa_uuid'),
        ),
        migrations.AddConstraint(
            model_name='hubfechamentodiarecebido',
            constraint=models.UniqueConstraint(fields=('hub', 'fechamento_uuid'), name='uq_hub_fech_dia_uuid'),
        ),
        migrations.AddIndex(
            model_name='hubeventorecebido',
            index=models.Index(fields=['hub', 'tipo'], name='ix_hub_evt_hub_tipo'),
        ),
        migrations.AddIndex(
            model_name='hubeventorecebido',
            index=models.Index(fields=['hub', 'status'], name='ix_hub_evt_hub_status'),
        ),
        migrations.AddConstraint(
            model_name='hubeventorecebido',
            constraint=models.UniqueConstraint(fields=('hub', 'evento_uuid'), name='uq_hub_evento_uuid'),
        ),
        migrations.AddConstraint(
            model_name='hubeventorecebido',
            constraint=models.UniqueConstraint(fields=('hub', 'chave_idempotencia'), name='uq_hub_chave_idempotencia'),
        ),
        migrations.AddConstraint(
            model_name='hubclientemapeamento',
            constraint=models.UniqueConstraint(fields=('hub', 'cliente_uuid'), name='uq_hub_cliente_uuid'),
        ),
    ]
