# Generated by Codex on 2026-09-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0040_nfce_hub_fields"),
        ("hub", "0003_hubvendamapeamento_hubsessaocaixarecebida_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubNFCeMapeamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nfce_uuid", models.UUIDField()),
                ("venda_uuid", models.UUIDField()),
                ("ultima_versao_evento", models.PositiveIntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("hub", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="nfces_mapeadas", to="hub.sysvarhub")),
                ("nfce", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="mapeamentos_hub", to="fiscal.nfce")),
            ],
        ),
        migrations.AddConstraint(
            model_name="hubnfcemapeamento",
            constraint=models.UniqueConstraint(fields=("hub", "nfce_uuid"), name="uq_hub_nfce_uuid"),
        ),
        migrations.AddConstraint(
            model_name="hubnfcemapeamento",
            constraint=models.UniqueConstraint(fields=("hub", "nfce"), name="uq_hub_nfce_central"),
        ),
    ]
