# Generated by Django 4.2.11 on 2026-09-20 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0040_nfce_hub_fields'),
        ('hub', '0004_hubnfcemapeamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubDevolucaoMapeamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devolucao_uuid', models.UUIDField()),
                ('venda_uuid', models.UUIDField()),
                ('documento', models.CharField(db_index=True, max_length=50)),
                ('vale_documento', models.CharField(blank=True, default='', max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeamentos_hub', to='fiscal.vendadevolucao')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_mapeadas', to='hub.sysvarhub')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hubdevolucaomapeamento',
            constraint=models.UniqueConstraint(fields=('hub', 'devolucao_uuid'), name='uq_hub_devolucao_uuid'),
        ),
        migrations.AddConstraint(
            model_name='hubdevolucaomapeamento',
            constraint=models.UniqueConstraint(fields=('hub', 'devolucao'), name='uq_hub_devolucao_central'),
        ),
    ]
