# Generated by Django 4.2.11 on 2026-09-21 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0005_hubdevolucaomapeamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSincronizacaoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPLETA', 'Completa')], default='COMPLETA', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=20)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('etapa_atual', models.CharField(blank=True, default='', max_length=80)),
                ('mensagem_erro', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sincronizacoes', to='hub.sysvarhub')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solicitado_em', '-id'],
                'indexes': [models.Index(fields=['hub', 'status'], name='ix_hub_sync_hub_status'), models.Index(fields=['status', 'solicitado_em'], name='ix_hub_sync_status_sol')],
            },
        ),
    ]
