# Generated by Django 4.2.11 on 2026-09-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_hubsincronizacaosolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysvarhub',
            name='snapshot_operacional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sysvarhub',
            name='snapshot_operacional_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
