# Generated by Django 4.2.11 on 2026-09-28 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0007_sysvarhub_snapshot_operacional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubComandoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONFIGURAR_TERMINAL', 'Configurar terminal'), ('GERAR_PAREAMENTO', 'Gerar pareamento')], db_index=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=20)),
                ('mensagem_erro', models.CharField(blank=True, default='', max_length=500)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandos_administrativos', to='hub.sysvarhub')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['solicitado_em', 'id'],
                'indexes': [models.Index(fields=['hub', 'status', 'tipo'], name='ix_hub_cmd_hub_status_tipo'), models.Index(fields=['hub', 'tipo', 'solicitado_em'], name='ix_hub_cmd_hub_tipo_sol')],
            },
        ),
    ]
