# Generated by Django 4.2.11 on 2025-11-07 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0006_produto_bloqueado_venda_and_more'),
        ('cadastros', '0002_nat_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'Revenda'), ('2', 'Uso/Consumo')], max_length=1)),
                ('emissao', models.DateField(default=django.utils.timezone.now)),
                ('previsao_entrega', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('AB', 'Aberto'), ('AP', 'Aprovado'), ('CA', 'Cancelado')], default='AB', max_length=2)),
                ('total_itens', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.loja')),
            ],
            options={
                'db_table': 'compras_pedido_compra',
                'ordering': ['-emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompraItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('n_packs', models.PositiveIntegerField(default=0)),
                ('descricao_livre', models.CharField(blank=True, max_length=200, null=True)),
                ('qtd', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('desconto_valor', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_item', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('cor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produto.cor')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produto.pack')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedidocompra')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produto.produto')),
            ],
            options={
                'db_table': 'compras_pedido_compra_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompraEntrega',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qtd_prevista', models.PositiveIntegerField(default=0)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('qtd_recebida', models.PositiveIntegerField(default=0)),
                ('data_recebida', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PREV', 'Prevista'), ('PARC', 'Parcial'), ('RECB', 'Recebida'), ('ATR', 'Atrasada')], default='PREV', max_length=4)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='compras.pedidocompraitem')),
            ],
            options={
                'db_table': 'compras_pedido_compra_entrega',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompraParcela',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parcela_n', models.PositiveIntegerField()),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origem', models.CharField(choices=[('FORMA', 'FORMA'), ('MANUAL', 'MANUAL')], default='FORMA', max_length=6)),
                ('status', models.CharField(choices=[('PLAN', 'Planejada'), ('GERADA', 'Gerada em Financeiro'), ('CANC', 'Cancelada')], default='PLAN', max_length=8)),
                ('pagar_item_id', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='compras.pedidocompra')),
            ],
            options={
                'db_table': 'compras_pedido_compra_parcela',
                'ordering': ['pedido_id', 'parcela_n'],
                'indexes': [models.Index(fields=['pedido', 'parcela_n'], name='compras_ped_pedido__1a0710_idx'), models.Index(fields=['status'], name='compras_ped_status_71f0c5_idx'), models.Index(fields=['vencimento'], name='compras_ped_vencime_82815c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pedidocompraparcela',
            constraint=models.UniqueConstraint(fields=('pedido', 'parcela_n'), name='uq_pc_parcela'),
        ),
    ]
