# Generated by Django 4.2.11 on 2026-08-19 14:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        ('produto', '0032_grade_uq_empresa_grade_descricao_aux_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0008_pedidocompra_emissao_localdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(db_index=True)),
                ('setor', models.CharField(max_length=80)),
                ('data_requisicao', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_necessaria', models.DateField(blank=True, db_index=True, null=True)),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('EMERGENCIAL', 'Emergencial')], db_index=True, default='NORMAL', max_length=12)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SOLICITADA', 'Solicitada'), ('EM_ANALISE', 'Em análise'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('APROVADA', 'Aprovada'), ('EM_ATENDIMENTO', 'Em atendimento'), ('ATENDIDA_PARCIALMENTE', 'Atendida parcialmente'), ('EM_PROCESSO_COMPRA', 'Em processo de compra'), ('EM_PROCESSO_CONTRATACAO', 'Em processo de contratação'), ('CONCLUIDA', 'Concluída'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], db_index=True, default='RASCUNHO', max_length=30)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_compra', to='cadastros.empresa')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_compra', to='cadastros.loja')),
                ('requisitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compras_requisicao',
                'ordering': ['-data_requisicao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoServicoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_servico_requisicao', to='cadastros.empresa')),
            ],
            options={
                'db_table': 'compras_requisicao_servico_categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('SERVICO', 'Serviço')], db_index=True, max_length=10)),
                ('origem', models.CharField(choices=[('PRODUTO', 'Produto cadastrado'), ('LIVRE', 'Item não cadastrado'), ('SERVICO', 'Serviço')], db_index=True, max_length=10)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('categoria', models.CharField(blank=True, default='', max_length=80)),
                ('especificacao_tecnica', models.TextField(blank=True, default='')),
                ('titulo_servico', models.CharField(blank=True, default='', max_length=160)),
                ('descricao_servico', models.TextField(blank=True, default='')),
                ('tipo_servico', models.CharField(blank=True, choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva'), ('INSTALACAO', 'Instalação'), ('REVISAO', 'Revisão'), ('REPARO', 'Reparo'), ('OUTRO', 'Outro')], default='', max_length=20)),
                ('qtd_solicitada', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('qtd_atendida', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('qtd_pendente', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_SEPARACAO', 'Em separação'), ('ATENDIDO', 'Atendido'), ('ATENDIDO_PARCIALMENTE', 'Atendido parcialmente'), ('AGUARDANDO_COTACAO', 'Aguardando cotação'), ('EM_COTACAO', 'Em cotação'), ('PEDIDO_GERADO', 'Pedido gerado'), ('AGUARDANDO_RECEBIMENTO', 'Aguardando recebimento'), ('RECEBIDO', 'Recebido'), ('SERVICO_CONTRATACAO', 'Serviço em contratação'), ('SERVICO_CONCLUIDO', 'Serviço concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=30)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao', to='compras.requisicaoservicocategoria')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao', to='produto.produto')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.requisicao')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao', to='produto.unidade')),
            ],
            options={
                'db_table': 'compras_requisicao_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoHistorico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('ENVIO', 'Envio'), ('APROVACAO', 'Aprovação'), ('REJEICAO', 'Rejeição'), ('DEVOLUCAO', 'Devolução'), ('ATENDIMENTO', 'Atendimento'), ('CANCELAMENTO', 'Cancelamento'), ('STATUS', 'Mudança de status')], db_index=True, max_length=20)),
                ('status_anterior', models.CharField(blank=True, default='', max_length=30)),
                ('status_novo', models.CharField(blank=True, default='', max_length=30)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_novo', models.JSONField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='compras.requisicaoitem')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='compras.requisicao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_requisicao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compras_requisicao_historico',
                'ordering': ['-data_hora', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='requisicaoservicocategoria',
            index=models.Index(fields=['empresa', 'ativo'], name='compras_req_empresa_31385a_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisicaoservicocategoria',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uq_req_serv_cat_empresa_nome'),
        ),
        migrations.AddIndex(
            model_name='requisicaoitem',
            index=models.Index(fields=['requisicao', 'status'], name='compras_req_requisi_d8d74a_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoitem',
            index=models.Index(fields=['produto'], name='compras_req_produto_ba7d72_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoitem',
            index=models.Index(fields=['tipo', 'origem'], name='compras_req_tipo_653a00_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaohistorico',
            index=models.Index(fields=['requisicao', '-data_hora'], name='compras_req_requisi_c42bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaohistorico',
            index=models.Index(fields=['acao', 'data_hora'], name='compras_req_acao_a42e29_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['empresa', 'status'], name='compras_req_empresa_375790_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['empresa', 'loja'], name='compras_req_empresa_093bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['requisitante', 'data_requisicao'], name='compras_req_requisi_11747d_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisicao',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uq_requisicao_empresa_numero'),
        ),
    ]
