# Generated by Django 4.2.11 on 2026-08-20 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


MATERIAL_CATEGORIAS_PADRAO = [
    "Informática",
    "Mobiliário",
    "Equipamentos",
    "Material de escritório",
    "Limpeza",
    "Segurança",
    "Comunicação",
    "Outros",
]

FINALIDADES_PADRAO = [
    ("Uso e Consumo", "USO_CONSUMO"),
    ("Estoque/Almoxarifado", "ALMOXARIFADO"),
    ("Imobilizado", "IMOBILIZADO"),
    ("Outro", "OUTRO"),
]


def seed_and_migrate_requisicao_refs(apps, schema_editor):
    Empresa = apps.get_model("cadastros", "Empresa")
    RequisicaoItem = apps.get_model("compras", "RequisicaoItem")
    RequisicaoMaterialCategoria = apps.get_model("compras", "RequisicaoMaterialCategoria")
    RequisicaoFinalidadeAquisicao = apps.get_model("compras", "RequisicaoFinalidadeAquisicao")

    for empresa in Empresa.objects.all().iterator():
        for nome in MATERIAL_CATEGORIAS_PADRAO:
            RequisicaoMaterialCategoria.objects.get_or_create(empresa_id=empresa.pk, nome=nome)
        for nome, comportamento in FINALIDADES_PADRAO:
            if not RequisicaoFinalidadeAquisicao.objects.filter(empresa_id=empresa.pk, comportamento=comportamento).exists():
                RequisicaoFinalidadeAquisicao.objects.create(empresa_id=empresa.pk, comportamento=comportamento, nome=nome)

    itens = RequisicaoItem.objects.select_related("requisicao").all()
    for item in itens.iterator():
        empresa_id = item.requisicao.empresa_id
        updates = {}
        categoria_texto = (item.categoria or "").strip()
        if categoria_texto and not item.categoria_material_id:
            categoria, _ = RequisicaoMaterialCategoria.objects.get_or_create(
                empresa_id=empresa_id,
                nome=categoria_texto,
            )
            updates["categoria_material_id"] = categoria.pk

        finalidade_codigo = (item.finalidade or "").strip()
        if finalidade_codigo and not item.finalidade_aquisicao_id:
            finalidade = RequisicaoFinalidadeAquisicao.objects.filter(
                empresa_id=empresa_id,
                comportamento=finalidade_codigo,
            ).first()
            if finalidade:
                updates["finalidade_aquisicao_id"] = finalidade.pk

        if updates:
            RequisicaoItem.objects.filter(pk=item.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        ('compras', '0012_requisicaoitem_finalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoMaterialCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_material_requisicao', to='cadastros.empresa')),
            ],
            options={
                'db_table': 'compras_requisicao_material_categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoFinalidadeAquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('comportamento', models.CharField(choices=[('USO_CONSUMO', 'Uso e Consumo'), ('ALMOXARIFADO', 'Estoque/Almoxarifado'), ('IMOBILIZADO', 'Imobilizado'), ('OUTRO', 'Outro')], db_index=True, max_length=20)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalidades_aquisicao', to='cadastros.empresa')),
            ],
            options={
                'db_table': 'compras_requisicao_finalidade_aquisicao',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='categoria_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao', to='compras.requisicaomaterialcategoria'),
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='finalidade_aquisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao', to='compras.requisicaofinalidadeaquisicao'),
        ),
        migrations.RunPython(seed_and_migrate_requisicao_refs, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='requisicaomaterialcategoria',
            index=models.Index(fields=['empresa', 'ativo'], name='compras_req_empresa_3b375f_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisicaomaterialcategoria',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uq_req_mat_cat_empresa_nome'),
        ),
        migrations.AddIndex(
            model_name='requisicaofinalidadeaquisicao',
            index=models.Index(fields=['empresa', 'ativo'], name='compras_req_empresa_96b19f_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaofinalidadeaquisicao',
            index=models.Index(fields=['empresa', 'comportamento'], name='compras_req_empresa_a365a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisicaofinalidadeaquisicao',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uq_req_fin_aq_empresa_nome'),
        ),
    ]
