# Generated by Django 4.2.11 on 2026-08-21 14:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0032_grade_uq_empresa_grade_descricao_aux_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        ('compras', '0014_requisicao_status_devolvida_correcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(blank=True, db_index=True)),
                ('data_abertura', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_limite_propostas', models.DateField(blank=True, db_index=True, null=True)),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('EMERGENCIAL', 'Emergencial')], db_index=True, default='NORMAL', max_length=12)),
                ('tipo_compra', models.CharField(choices=[('REVENDA', 'Revenda'), ('USO_CONSUMO', 'Uso/Consumo'), ('INSUMO', 'Insumo'), ('SERVICO', 'Serviço'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('EM_ELABORACAO', 'Em elaboração'), ('ABERTA', 'Aberta'), ('PROPOSTAS_RECEBIDAS', 'Propostas recebidas'), ('EM_ANALISE', 'Em análise'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada'), ('PEDIDO_GERADO', 'Pedido gerado'), ('ENCERRADA', 'Encerrada')], db_index=True, default='EM_ELABORACAO', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to='cadastros.empresa')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to='cadastros.loja')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compras_cotacao',
                'ordering': ['-data_abertura', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('quantidade_cotar', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('especificacao_tecnica', models.TextField(blank=True, default='')),
                ('marca_desejada', models.CharField(blank=True, default='', max_length=120)),
                ('modelo_referencia', models.CharField(blank=True, default='', max_length=120)),
                ('permite_alternativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('origem', models.CharField(choices=[('REQUISICAO', 'Requisição'), ('AVULSO', 'Avulso')], db_index=True, default='AVULSO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.cotacao')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_cotacao', to='produto.produto')),
                ('requisicao_item_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_cotacao', to='compras.requisicaoitem')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_cotacao', to='produto.unidade')),
            ],
            options={
                'db_table': 'compras_cotacao_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoRequisicao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_vinculadas', to='compras.cotacao')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_vinculadas', to='compras.requisicao')),
            ],
            options={
                'db_table': 'compras_cotacao_requisicao',
                'indexes': [models.Index(fields=['cotacao'], name='compras_cot_cotacao_14e596_idx'), models.Index(fields=['requisicao'], name='compras_cot_requisi_55d658_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cotacaorequisicao',
            constraint=models.UniqueConstraint(fields=('cotacao', 'requisicao'), name='uq_cotacao_requisicao'),
        ),
        migrations.AddIndex(
            model_name='cotacaoitem',
            index=models.Index(fields=['cotacao'], name='compras_cot_cotacao_227be8_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacaoitem',
            index=models.Index(fields=['produto'], name='compras_cot_produto_84e83b_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacaoitem',
            index=models.Index(fields=['origem'], name='compras_cot_origem_ea90ab_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['empresa', 'status'], name='compras_cot_empresa_66a82f_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['empresa', 'loja'], name='compras_cot_empresa_1f9d55_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['responsavel', 'data_abertura'], name='compras_cot_respons_494479_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotacao',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uq_cotacao_empresa_numero'),
        ),
    ]
