# Generated by Django 4.2.11 on 2026-08-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        ('compras', '0015_cotacao_cotacaoitem_cotacaorequisicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_participacao', models.CharField(choices=[('CONVIDADO', 'Convidado'), ('PROPOSTA_RECEBIDA', 'Proposta recebida'), ('NAO_RESPONDEU', 'Não respondeu'), ('RECUSOU', 'Recusou'), ('DESCLASSIFICADO', 'Desclassificado')], db_index=True, default='CONVIDADO', max_length=20)),
                ('motivo_desclassificacao', models.TextField(blank=True, default='')),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_participantes', to='compras.cotacao')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_participantes', to='cadastros.fornecedor')),
            ],
            options={
                'db_table': 'compras_cotacao_fornecedor',
                'indexes': [models.Index(fields=['cotacao', 'status_participacao'], name='compras_cot_cotacao_b99194_idx'), models.Index(fields=['fornecedor'], name='compras_cot_fornece_fb8907_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cotacaofornecedor',
            constraint=models.UniqueConstraint(fields=('cotacao', 'fornecedor'), name='uq_cotacao_fornecedor'),
        ),
    ]
