# Generated by Django 4.2.11 on 2026-08-21 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_cotacaofornecedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoProposta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_proposta', models.DateField(default=django.utils.timezone.localdate)),
                ('validade_proposta', models.DateField(blank=True, null=True)),
                ('prazo_entrega', models.CharField(blank=True, default='', max_length=120)),
                ('condicao_pagamento', models.CharField(blank=True, default='', max_length=160)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto_geral', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_itens', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_proposta', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observacao', models.TextField(blank=True, default='')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='cotacoes/propostas/')),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='compras.cotacao')),
                ('cotacao_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='compras.cotacaofornecedor')),
            ],
            options={
                'db_table': 'compras_cotacao_proposta',
            },
        ),
        migrations.CreateModel(
            name='CotacaoPropostaItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade_ofertada', models.DecimalField(decimal_places=3, max_digits=14)),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('marca', models.CharField(blank=True, default='', max_length=120)),
                ('modelo_referencia', models.CharField(blank=True, default='', max_length=120)),
                ('garantia', models.CharField(blank=True, default='', max_length=120)),
                ('prazo_entrega_item', models.CharField(blank=True, default='', max_length=120)),
                ('observacao', models.TextField(blank=True, default='')),
                ('total_item', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cotacao_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas_itens', to='compras.cotacaoitem')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.cotacaoproposta')),
            ],
            options={
                'db_table': 'compras_cotacao_proposta_item',
                'indexes': [models.Index(fields=['proposta'], name='compras_cot_propost_6adcf7_idx'), models.Index(fields=['cotacao_item'], name='compras_cot_cotacao_2a69a5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cotacaopropostaitem',
            constraint=models.UniqueConstraint(fields=('proposta', 'cotacao_item'), name='uq_cotacao_proposta_item'),
        ),
        migrations.AddIndex(
            model_name='cotacaoproposta',
            index=models.Index(fields=['cotacao', 'ativa'], name='compras_cot_cotacao_ac4ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacaoproposta',
            index=models.Index(fields=['cotacao_fornecedor'], name='compras_cot_cotacao_7ad37d_idx'),
        ),
    ]
