# Generated by Django 4.2.11 on 2026-08-21 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0017_cotacaoproposta_cotacaopropostaitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='justificativa_vencedor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='proposta_vencedora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_vencedoras', to='compras.cotacaoproposta'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='rejeitado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='rejeitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_rejeitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='snapshot_proposta_aprovada',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
