# Generated by Django 4.2.11 on 2026-08-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_cotacao_aprovado_em_cotacao_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='cotacao_origem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_compra_gerado', to='compras.cotacao'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='outras_despesas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
