# Generated by Django 4.2.11 on 2026-08-21 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0019_pedidocompra_cotacao_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, default=''),
        ),
    ]
