# Generated by Django 4.2.11 on 2026-08-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        ('compras', '0023_pedidocompraitem_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoMatrizResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_requisicao', models.CharField(choices=[('USO_CONSUMO', 'Uso e Consumo'), ('MANUTENCAO', 'Manutenção'), ('TI', 'TI')], db_index=True, max_length=20)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compras_requisicao_matriz_responsabilidade',
                'ordering': ['tipo_requisicao'],
            },
        ),
        migrations.AddField(
            model_name='requisicao',
            name='setor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_atendimento', to='compras.requisicaosetor'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='tipo_requisicao',
            field=models.CharField(choices=[('USO_CONSUMO', 'Uso e Consumo'), ('MANUTENCAO', 'Manutenção'), ('TI', 'TI')], db_index=True, default='USO_CONSUMO', max_length=20),
        ),
        migrations.AddField(
            model_name='requisicaosetor',
            name='central_manutencao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisicaosetor',
            name='central_ti',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisicaosetor',
            name='central_uso_consumo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisicaosetor',
            name='responsavel_compras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['empresa', 'tipo_requisicao'], name='compras_req_empresa_ff4097_idx'),
        ),
        migrations.AddField(
            model_name='requisicaomatrizresponsabilidade',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrizes_requisicao', to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='requisicaomatrizresponsabilidade',
            name='setor_aquisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrizes_aquisicao', to='compras.requisicaosetor'),
        ),
        migrations.AddField(
            model_name='requisicaomatrizresponsabilidade',
            name='setor_atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrizes_atendimento', to='compras.requisicaosetor'),
        ),
        migrations.AddIndex(
            model_name='requisicaomatrizresponsabilidade',
            index=models.Index(fields=['empresa', 'ativo'], name='compras_req_empresa_f769e4_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaomatrizresponsabilidade',
            index=models.Index(fields=['empresa', 'tipo_requisicao'], name='compras_req_empresa_3d8ec0_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisicaomatrizresponsabilidade',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_requisicao'), name='uq_req_matriz_empresa_tipo'),
        ),
    ]
