# Generated by Django 4.2.11 on 2026-08-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        ('compras', '0024_requisicaomatrizresponsabilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaosetor',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setores_requisicao', to='cadastros.loja'),
        ),
    ]
