# Generated by Django 4.2.11 on 2026-08-24 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_corrige_comissao_gerente_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0025_requisicaosetor_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('USO_CONSUMO', 'Uso e Consumo'), ('MANUTENCAO', 'Manutenção'), ('TI', 'TI')], db_index=True, max_length=20)),
                ('origem', models.CharField(db_index=True, default='REQUISICAO', max_length=20)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_TRIAGEM', 'Em triagem'), ('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO_MATERIAL', 'Aguardando material'), ('AGUARDANDO_TERCEIRO', 'Aguardando terceiro'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABERTA', max_length=30)),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('solucao', models.TextField(blank=True, default='')),
                ('previsao_atendimento', models.DateTimeField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='cadastros.empresa')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='cadastros.loja')),
                ('requisicao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico', to='compras.requisicao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_responsavel', to=settings.AUTH_USER_MODEL)),
                ('setor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_responsaveis', to='compras.requisicaosetor')),
                ('setor_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_solicitadas', to='compras.requisicaosetor')),
            ],
            options={
                'db_table': 'compras_ordem_servico',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='compras_ord_empresa_6ca69b_idx'), models.Index(fields=['empresa', 'tipo'], name='compras_ord_empresa_5bf643_idx'), models.Index(fields=['loja', 'status'], name='compras_ord_loja_id_e366a8_idx'), models.Index(fields=['setor_responsavel', 'status'], name='compras_ord_setor_r_283445_idx')],
            },
        ),
    ]
