# Generated by Django 4.2.11 on 2026-08-24 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0032_grade_uq_empresa_grade_descricao_aux_and_more'),
        ('compras', '0026_ordemservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoMaterial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('qtd_necessaria', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('qtd_atendida', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('qtd_pendente', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DISPONIVEL', 'Disponível'), ('EM_COMPRA', 'Em compra'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='compras.ordemservico')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='necessidades_os', to='produto.produto')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='necessidades_os', to='produto.unidade')),
            ],
            options={
                'db_table': 'compras_ordem_servico_material',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['ordem_servico', 'status'], name='compras_ord_ordem_s_84e17b_idx'), models.Index(fields=['produto'], name='compras_ord_produto_106104_idx')],
            },
        ),
    ]
