# Generated by Django 4.2.11 on 2026-08-24 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0027_ordemservicomaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaoitem',
            name='ordem_servico_material_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_cotacao', to='compras.ordemservicomaterial'),
        ),
        migrations.AlterField(
            model_name='cotacaoitem',
            name='origem',
            field=models.CharField(choices=[('REQUISICAO', 'Requisição'), ('OS', 'Ordem de Serviço'), ('AVULSO', 'Avulso')], db_index=True, default='AVULSO', max_length=10),
        ),
    ]
