from django.urls import path

from hub.views import (
    HubAdministracaoAcaoView,
    HubAdministracaoComandoView,
    HubAdministracaoConfigurarTerminalView,
    HubAdministracaoPareamentoView,
    HubAdministracaoView,
    HubAtivacaoAdminView,
    HubAtivacaoRevogarView,
    HubAtivarView,
    HubBootstrapView,
    HubCatalogoView,
    HubCatalogoImagemView,
    HubClientesView,
    HubDevolucaoClienteVendasView,
    HubDevolucaoClientesView,
    HubDevolucaoFaixaNumeracaoView,
    HubDevolucaoFinalizarOnlineView,
    HubDevolucaoVendaDetalheView,
    HubDevolucaoVendaView,
    HubFormasPagamentoView,
    HubHeartbeatView,
    HubComandoAdministrativoResultadoView,
    HubOperadoresView,
    HubSincronizacaoPainelView,
    HubSincronizacaoSolicitarView,
    HubSincronizacaoStatusView,
    HubSincronizacaoTodasView,
    HubSyncPushView,
    HubTiposDespesaPdvView,
    HubValeTrocaCancelarReservaView,
    HubValeTrocaCancelarVendaView,
    HubValeTrocaConsultarView,
    HubValeTrocaDisponiveisView,
    HubValeTrocaReservarVendaView,
    HubValeTrocaReservasVendaView,
    HubVendedoresView,
    HubVendaFaixaNumeracaoView,
)

urlpatterns = [
    path("administracao/", HubAdministracaoView.as_view(), name="hub-administracao"),
    path(
        "administracao/<int:hub_id>/desativar/",
        HubAdministracaoAcaoView.as_view(acao="desativar"),
        name="hub-administracao-desativar",
    ),
    path(
        "administracao/<int:hub_id>/reativar/",
        HubAdministracaoAcaoView.as_view(acao="reativar"),
        name="hub-administracao-reativar",
    ),
    path(
        "administracao/<int:hub_id>/desvincular/",
        HubAdministracaoAcaoView.as_view(acao="desvincular"),
        name="hub-administracao-desvincular",
    ),
    path(
        "administracao/<int:hub_id>/terminais/configurar/",
        HubAdministracaoConfigurarTerminalView.as_view(),
        name="hub-administracao-configurar-terminal",
    ),
    path(
        "administracao/<int:hub_id>/terminais/pareamento/",
        HubAdministracaoPareamentoView.as_view(),
        name="hub-administracao-pareamento",
    ),
    path("administracao/comandos/<int:comando_id>/", HubAdministracaoComandoView.as_view(), name="hub-administracao-comando"),
    path("ativacoes/", HubAtivacaoAdminView.as_view(), name="hub-ativacoes"),
    path("ativacoes/<int:ativacao_id>/revogar/", HubAtivacaoRevogarView.as_view(), name="hub-ativacoes-revogar"),
    path("ativar/", HubAtivarView.as_view(), name="hub-ativar"),
    path("bootstrap/", HubBootstrapView.as_view(), name="hub-bootstrap"),
    path("catalogo/", HubCatalogoView.as_view(), name="hub-catalogo"),
    path("catalogo/imagens/<int:imagem_id>/", HubCatalogoImagemView.as_view(), name="hub-catalogo-imagem"),
    path("clientes/", HubClientesView.as_view(), name="hub-clientes"),
    path("devolucoes/vendas/", HubDevolucaoVendaView.as_view(), name="hub-devolucao-venda"),
    path("devolucoes/vendas/<int:venda_id>/", HubDevolucaoVendaDetalheView.as_view(), name="hub-devolucao-venda-detalhe"),
    path("devolucoes/clientes/", HubDevolucaoClientesView.as_view(), name="hub-devolucao-clientes"),
    path("devolucoes/clientes/<int:cliente_id>/vendas/", HubDevolucaoClienteVendasView.as_view(), name="hub-devolucao-cliente-vendas"),
    path("devolucoes/finalizar/", HubDevolucaoFinalizarOnlineView.as_view(), name="hub-devolucao-finalizar"),
    path("devolucoes/faixa-numeracao/", HubDevolucaoFaixaNumeracaoView.as_view(), name="hub-devolucoes-faixa-numeracao"),
    path("formas-pagamento/", HubFormasPagamentoView.as_view(), name="hub-formas-pagamento"),
    path("vales-troca/consultar/", HubValeTrocaConsultarView.as_view(), name="hub-vale-troca-consultar"),
    path("vales-troca/disponiveis/", HubValeTrocaDisponiveisView.as_view(), name="hub-vale-troca-disponiveis"),
    path("vales-troca/reservar-venda/", HubValeTrocaReservarVendaView.as_view(), name="hub-vale-troca-reservar-venda"),
    path("vales-troca/reservas/<uuid:venda_uuid>/", HubValeTrocaReservasVendaView.as_view(), name="hub-vale-troca-reservas-venda"),
    path("vales-troca/cancelar-reserva/", HubValeTrocaCancelarReservaView.as_view(), name="hub-vale-troca-cancelar-reserva"),
    path("vales-troca/cancelar-venda/", HubValeTrocaCancelarVendaView.as_view(), name="hub-vale-troca-cancelar-venda"),
    path("heartbeat/", HubHeartbeatView.as_view(), name="hub-heartbeat"),
    path("comandos/<int:comando_id>/resultado/", HubComandoAdministrativoResultadoView.as_view(), name="hub-comando-resultado"),
    path("sincronizacoes/", HubSincronizacaoPainelView.as_view(), name="hub-sincronizacoes"),
    path("sincronizacoes/solicitar/", HubSincronizacaoSolicitarView.as_view(), name="hub-sincronizacoes-solicitar"),
    path("sincronizacoes/todas/", HubSincronizacaoTodasView.as_view(), name="hub-sincronizacoes-todas"),
    path("sincronizacoes/<int:sincronizacao_id>/status/", HubSincronizacaoStatusView.as_view(), name="hub-sincronizacoes-status"),
    path("sync/push/", HubSyncPushView.as_view(), name="hub-sync-push"),
    path("vendas/faixa-numeracao/", HubVendaFaixaNumeracaoView.as_view(), name="hub-vendas-faixa-numeracao"),
    path("operadores/", HubOperadoresView.as_view(), name="hub-operadores"),
    path("tipos-despesa-pdv/", HubTiposDespesaPdvView.as_view(), name="hub-tipos-despesa-pdv"),
    path("vendedores/", HubVendedoresView.as_view(), name="hub-vendedores"),
]
